export type Name99 = {
  number: number;
  arabic: string;
  transliteration: string;
  meaning: string;
  description: string;
};

export const ASMAUL_HUSNA: Name99[] = [
  { number: 1,  arabic: 'الرَّحْمَٰن',        transliteration: 'Ar-Rahman',           meaning: 'The Most Gracious',           description: 'The One who has vast mercy for all creation in this world and the next.' },
  { number: 2,  arabic: 'الرَّحِيم',           transliteration: 'Ar-Raheem',           meaning: 'The Most Merciful',           description: 'The One whose mercy is specifically reserved for the believers in the Hereafter.' },
  { number: 3,  arabic: 'الْمَلِك',            transliteration: 'Al-Malik',            meaning: 'The King',                    description: 'The Sovereign Lord who owns and governs all of creation.' },
  { number: 4,  arabic: 'الْقُدُّوس',          transliteration: 'Al-Quddus',           meaning: 'The Most Holy',               description: 'The One who is free from every imperfection, deficiency, and partner.' },
  { number: 5,  arabic: 'السَّلَام',           transliteration: 'As-Salam',            meaning: 'The Source of Peace',         description: 'The One who is free from all defects and who grants peace to His servants.' },
  { number: 6,  arabic: 'الْمُؤْمِن',          transliteration: "Al-Mu'min",           meaning: 'The Granter of Security',     description: 'The One who gives security and safety to His creation.' },
  { number: 7,  arabic: 'الْمُهَيْمِن',        transliteration: 'Al-Muhaymin',         meaning: 'The Protector',               description: 'The One who watches over and protects all things.' },
  { number: 8,  arabic: 'الْعَزِيز',           transliteration: "Al-'Aziz",            meaning: 'The Almighty',                description: 'The One who is invincible and whose will is never prevented.' },
  { number: 9,  arabic: 'الْجَبَّار',          transliteration: 'Al-Jabbar',           meaning: 'The Compeller',               description: 'The One who mends the broken and compels things to be as He wills.' },
  { number: 10, arabic: 'الْمُتَكَبِّر',       transliteration: 'Al-Mutakabbir',       meaning: 'The Supreme',                 description: 'The One who manifests His greatness in all things. Greatness belongs to Him alone.' },
  { number: 11, arabic: 'الْخَالِق',           transliteration: 'Al-Khaliq',           meaning: 'The Creator',                 description: 'The One who brings into existence from nothing, having determined all measures.' },
  { number: 12, arabic: 'الْبَارِئ',           transliteration: "Al-Bari'",            meaning: 'The Originator',              description: 'The One who originates creation according to His will without any model.' },
  { number: 13, arabic: 'الْمُصَوِّر',         transliteration: 'Al-Musawwir',         meaning: 'The Fashioner',               description: 'The One who gives everything its unique shape, form and image.' },
  { number: 14, arabic: 'الْغَفَّار',          transliteration: 'Al-Ghaffar',          meaning: 'The All-Forgiving',           description: 'The One who forgives repeatedly, covering sins with His vast forgiveness.' },
  { number: 15, arabic: 'الْقَهَّار',          transliteration: 'Al-Qahhar',           meaning: 'The Subduer',                 description: 'The One who subdues and overpowers everything in creation.' },
  { number: 16, arabic: 'الْوَهَّاب',          transliteration: 'Al-Wahhab',           meaning: 'The Bestower',                description: 'The One who gives freely and continuously without expecting any return.' },
  { number: 17, arabic: 'الرَّزَّاق',          transliteration: 'Ar-Razzaq',           meaning: 'The Provider',                description: 'The One who provides sustenance for all of creation without limit.' },
  { number: 18, arabic: 'الْفَتَّاح',          transliteration: 'Al-Fattah',           meaning: 'The Opener',                  description: 'The One who opens the gates of mercy, provision, and knowledge for His servants.' },
  { number: 19, arabic: 'الْعَلِيم',           transliteration: "Al-'Alim",            meaning: 'The All-Knowing',             description: 'The One whose knowledge encompasses everything — past, present, and future.' },
  { number: 20, arabic: 'الْقَابِض',           transliteration: 'Al-Qabid',            meaning: 'The Withholder',              description: 'The One who withholds and constricts by His wisdom and in accordance with His will.' },
  { number: 21, arabic: 'الْبَاسِط',           transliteration: 'Al-Basit',            meaning: 'The Extender',                description: 'The One who extends provision, mercy, and blessings to whom He wills.' },
  { number: 22, arabic: 'الْخَافِض',           transliteration: 'Al-Khafid',           meaning: 'The Abaser',                  description: 'The One who lowers the oppressors and the arrogant.' },
  { number: 23, arabic: 'الرَّافِع',           transliteration: "Ar-Rafi'",            meaning: 'The Exalter',                 description: 'The One who raises the believers, the righteous, and the humble.' },
  { number: 24, arabic: 'الْمُعِزّ',           transliteration: "Al-Mu'izz",           meaning: 'The Bestower of Honor',       description: 'The One who grants honor and dignity to whom He wills.' },
  { number: 25, arabic: 'الْمُذِلّ',           transliteration: 'Al-Mudhill',          meaning: 'The Humiliator',              description: 'The One who humiliates and disgraces those who oppose His will.' },
  { number: 26, arabic: 'السَّمِيع',           transliteration: "As-Sami'",            meaning: 'The All-Hearing',             description: 'The One who hears all things — the spoken and the unspoken.' },
  { number: 27, arabic: 'الْبَصِير',           transliteration: 'Al-Basir',            meaning: 'The All-Seeing',              description: 'The One who sees all things, even what is hidden in the darkest darkness.' },
  { number: 28, arabic: 'الْحَكَم',            transliteration: 'Al-Hakam',            meaning: 'The Judge',                   description: 'The One who judges between His creation with perfect justice.' },
  { number: 29, arabic: 'الْعَدْل',            transliteration: "Al-'Adl",             meaning: 'The Just',                    description: 'The One who is perfectly just in all His actions and decrees.' },
  { number: 30, arabic: 'اللَّطِيف',           transliteration: 'Al-Latif',            meaning: 'The Subtle One',              description: 'The One who is kind and gentle, knowing the finest details of all things.' },
  { number: 31, arabic: 'الْخَبِير',           transliteration: 'Al-Khabir',           meaning: 'The All-Aware',               description: 'The One who is fully aware of all things, including what is hidden from all.' },
  { number: 32, arabic: 'الْحَلِيم',           transliteration: 'Al-Halim',            meaning: 'The Forbearing',              description: 'The One who delays punishment out of forbearance, giving time to repent.' },
  { number: 33, arabic: 'الْعَظِيم',           transliteration: "Al-'Azim",            meaning: 'The Magnificent',             description: 'The One who is great beyond all comprehension and imagination.' },
  { number: 34, arabic: 'الْغَفُور',           transliteration: 'Al-Ghafur',           meaning: 'The Forgiving',               description: 'The One who forgives sins no matter how great, for those who repent.' },
  { number: 35, arabic: 'الشَّكُور',           transliteration: 'Ash-Shakur',          meaning: 'The Appreciative',            description: 'The One who rewards abundantly even small acts of obedience and gratitude.' },
  { number: 36, arabic: 'الْعَلِيّ',           transliteration: "Al-'Aliyy",           meaning: 'The Most High',               description: 'The One who is exalted above all His creation in His essence and attributes.' },
  { number: 37, arabic: 'الْكَبِير',           transliteration: 'Al-Kabir',            meaning: 'The Most Great',              description: 'The One who is greater than everything in every way.' },
  { number: 38, arabic: 'الْحَفِيظ',           transliteration: 'Al-Hafiz',            meaning: 'The Preserver',               description: 'The One who preserves and protects all things from loss and ruin.' },
  { number: 39, arabic: 'الْمُقِيت',           transliteration: 'Al-Muqit',            meaning: 'The Nourisher',               description: 'The One who provides nourishment, sustenance, and strength to all.' },
  { number: 40, arabic: 'الْحَسِيب',           transliteration: 'Al-Hasib',            meaning: 'The Reckoner',                description: 'The One who takes account of all deeds and is sufficient for His servants.' },
  { number: 41, arabic: 'الْجَلِيل',           transliteration: 'Al-Jalil',            meaning: 'The Majestic',                description: 'The One who possesses absolute majesty, greatness, and glory.' },
  { number: 42, arabic: 'الْكَرِيم',           transliteration: 'Al-Karim',            meaning: 'The Most Generous',           description: 'The One who is noble, generous, and gives more than what is asked.' },
  { number: 43, arabic: 'الرَّقِيب',           transliteration: 'Ar-Raqib',            meaning: 'The Watchful',                description: 'The One who watches over all things and nothing escapes His observation.' },
  { number: 44, arabic: 'الْمُجِيب',           transliteration: 'Al-Mujib',            meaning: 'The Responsive',              description: 'The One who responds to the prayers and supplications of His servants.' },
  { number: 45, arabic: 'الْوَاسِع',           transliteration: "Al-Wasi'",            meaning: 'The All-Encompassing',        description: 'The One whose knowledge, mercy, and sustenance encompass all things.' },
  { number: 46, arabic: 'الْحَكِيم',           transliteration: 'Al-Hakim',            meaning: 'The All-Wise',                description: 'The One whose every decree and action is based on perfect wisdom.' },
  { number: 47, arabic: 'الْوَدُود',           transliteration: 'Al-Wadud',            meaning: 'The Loving',                  description: 'The One who loves His righteous servants with a love beyond all measure.' },
  { number: 48, arabic: 'الْمَجِيد',           transliteration: 'Al-Majid',            meaning: 'The Most Glorious',           description: 'The One who is glorious in His essence, attributes, and actions.' },
  { number: 49, arabic: 'الْبَاعِث',           transliteration: "Al-Ba'ith",           meaning: 'The Resurrector',             description: 'The One who will resurrect all creation on the Day of Judgment.' },
  { number: 50, arabic: 'الشَّهِيد',           transliteration: 'Ash-Shahid',          meaning: 'The Witness',                 description: 'The One who is witness to everything — all deeds, words, and thoughts.' },
  { number: 51, arabic: 'الْحَقّ',             transliteration: 'Al-Haqq',             meaning: 'The Truth',                   description: 'The One who is the absolute truth and whose promises are always fulfilled.' },
  { number: 52, arabic: 'الْوَكِيل',           transliteration: 'Al-Wakil',            meaning: 'The Trustee',                 description: 'The One who is the best trustee for managing the affairs of His servants.' },
  { number: 53, arabic: 'الْقَوِيّ',           transliteration: "Al-Qawiyy",           meaning: 'The Most Strong',             description: 'The One who has perfect and complete power over all things.' },
  { number: 54, arabic: 'الْمَتِين',           transliteration: 'Al-Matin',            meaning: 'The Firm',                    description: 'The One whose strength is firm and steadfast and never weakens.' },
  { number: 55, arabic: 'الْوَلِيّ',           transliteration: "Al-Waliyy",           meaning: 'The Protecting Friend',       description: 'The One who is the Guardian and Protector of the believers.' },
  { number: 56, arabic: 'الْحَمِيد',           transliteration: 'Al-Hamid',            meaning: 'The Praiseworthy',            description: 'The One who is deserving of all praise and thanks at all times.' },
  { number: 57, arabic: 'الْمُحْصِي',          transliteration: 'Al-Muhsi',            meaning: 'The All-Enumerating',         description: 'The One who keeps precise count of everything in creation.' },
  { number: 58, arabic: 'الْمُبْدِئ',          transliteration: "Al-Mubdi'",           meaning: 'The Originator',              description: 'The One who begins creation from nothing.' },
  { number: 59, arabic: 'الْمُعِيد',           transliteration: "Al-Mu'id",            meaning: 'The Restorer',                description: 'The One who restores creation after its death on the Day of Resurrection.' },
  { number: 60, arabic: 'الْمُحْيِي',          transliteration: 'Al-Muhyi',            meaning: 'The Giver of Life',           description: 'The One who gives life to what was dead — in this world and the Hereafter.' },
  { number: 61, arabic: 'الْمُمِيت',           transliteration: 'Al-Mumit',            meaning: 'The Bringer of Death',        description: 'The One who causes death to all living things by His command.' },
  { number: 62, arabic: 'الْحَيّ',             transliteration: 'Al-Hayy',             meaning: 'The Ever-Living',             description: 'The One who is alive with a life that has no beginning or end.' },
  { number: 63, arabic: 'الْقَيُّوم',          transliteration: 'Al-Qayyum',           meaning: 'The Self-Subsisting',         description: 'The One who sustains Himself and upon whom all creation depends.' },
  { number: 64, arabic: 'الْوَاجِد',           transliteration: 'Al-Wajid',            meaning: 'The Finder',                  description: 'The One who is self-sufficient and finds whatever He wills.' },
  { number: 65, arabic: 'الْمَاجِد',           transliteration: 'Al-Majid',            meaning: 'The Noble',                   description: 'The One who is noble and generous, combining glory with graciousness.' },
  { number: 66, arabic: 'الْوَاحِد',           transliteration: 'Al-Wahid',            meaning: 'The One',                     description: 'The One who has no partner, associate, or equal in any way.' },
  { number: 67, arabic: 'الْأَحَد',            transliteration: 'Al-Ahad',             meaning: 'The Unique',                  description: 'The One who is uniquely one — unlike anything in creation.' },
  { number: 68, arabic: 'الصَّمَد',            transliteration: 'As-Samad',            meaning: 'The Eternal',                 description: 'The One who is self-sufficient and whom all of creation turns to in need.' },
  { number: 69, arabic: 'الْقَادِر',           transliteration: 'Al-Qadir',            meaning: 'The Capable',                 description: 'The One who is able to do whatever He wills, when He wills.' },
  { number: 70, arabic: 'الْمُقْتَدِر',        transliteration: 'Al-Muqtadir',         meaning: 'The All-Powerful',            description: 'The One whose power is absolute and manifests in all things.' },
  { number: 71, arabic: 'الْمُقَدِّم',         transliteration: 'Al-Muqaddim',         meaning: 'The Expediter',               description: 'The One who brings forward what He wills and expedites whom He chooses.' },
  { number: 72, arabic: 'الْمُؤَخِّر',         transliteration: "Al-Mu'akhkhir",       meaning: 'The Delayer',                 description: 'The One who delays what He wills according to His perfect wisdom.' },
  { number: 73, arabic: 'الْأَوَّل',           transliteration: 'Al-Awwal',            meaning: 'The First',                   description: 'The One before whom there is nothing — He has always existed.' },
  { number: 74, arabic: 'الْآخِر',             transliteration: 'Al-Akhir',            meaning: 'The Last',                    description: 'The One after whom there is nothing — He will remain after everything ends.' },
  { number: 75, arabic: 'الظَّاهِر',           transliteration: 'Az-Zahir',            meaning: 'The Manifest',                description: 'The One who is apparent through His signs, creation, and attributes.' },
  { number: 76, arabic: 'الْبَاطِن',           transliteration: 'Al-Batin',            meaning: 'The Hidden',                  description: 'The One whose essence is hidden and cannot be perceived by human senses.' },
  { number: 77, arabic: 'الْوَالِي',           transliteration: 'Al-Wali',             meaning: 'The Governor',                description: 'The One who governs and directs all affairs of the universe.' },
  { number: 78, arabic: 'الْمُتَعَالِي',       transliteration: "Al-Muta'ali",         meaning: 'The Most Exalted',            description: 'The One who is exalted above all comparison and resemblance.' },
  { number: 79, arabic: 'الْبَرّ',             transliteration: 'Al-Barr',             meaning: 'The Source of All Good',      description: 'The One who is kind and good to His servants in ways they cannot count.' },
  { number: 80, arabic: 'التَّوَّاب',          transliteration: 'At-Tawwab',           meaning: 'The Acceptor of Repentance',  description: 'The One who repeatedly accepts repentance and returns to His servant with mercy.' },
  { number: 81, arabic: 'الْمُنْتَقِم',        transliteration: 'Al-Muntaqim',         meaning: 'The Avenger',                 description: 'The One who takes retribution from those who persist in wrongdoing.' },
  { number: 82, arabic: 'الْعَفُوّ',           transliteration: "Al-'Afu",             meaning: 'The Pardoner',                description: 'The One who pardons and erases sins, leaving no trace of them.' },
  { number: 83, arabic: 'الرَّؤُوف',           transliteration: "Ar-Ra'uf",            meaning: 'The Most Kind',               description: 'The One who is extremely compassionate and tender toward His servants.' },
  { number: 84, arabic: 'مَالِكُ الْمُلْك',    transliteration: 'Malik-ul-Mulk',       meaning: 'Owner of All Sovereignty',    description: 'The One who owns all dominion and grants or takes it as He wills.' },
  { number: 85, arabic: 'ذُو الْجَلَالِ وَالْإِكْرَام', transliteration: 'Dhul-Jalali wal-Ikram', meaning: 'Lord of Majesty & Generosity', description: 'The One who combines perfect majesty and infinite generosity.' },
  { number: 86, arabic: 'الْمُقْسِط',          transliteration: 'Al-Muqsit',           meaning: 'The Equitable',               description: 'The One who acts with perfect equity and fairness in all His judgments.' },
  { number: 87, arabic: 'الْجَامِع',           transliteration: "Al-Jami'",            meaning: 'The Gatherer',                description: 'The One who will gather all of creation on the Day of Resurrection.' },
  { number: 88, arabic: 'الْغَنِيّ',           transliteration: "Al-Ghaniyy",          meaning: 'The Self-Sufficient',         description: 'The One who is free of all needs and is not dependent on anything.' },
  { number: 89, arabic: 'الْمُغْنِي',          transliteration: 'Al-Mughni',           meaning: 'The Enricher',                description: 'The One who enriches and fulfills the needs of His servants.' },
  { number: 90, arabic: 'الْمَانِع',           transliteration: "Al-Mani'",            meaning: 'The Preventer',               description: 'The One who withholds or grants based on His wisdom and mercy.' },
  { number: 91, arabic: 'الضَّارّ',            transliteration: 'Ad-Darr',             meaning: 'The Distresser',              description: 'The One who creates harm for those He wills as part of His wisdom and justice.' },
  { number: 92, arabic: 'النَّافِع',           transliteration: "An-Nafi'",            meaning: 'The Propitious',              description: 'The One who creates benefit for whom He wills from His servants.' },
  { number: 93, arabic: 'النُّور',             transliteration: 'An-Nur',              meaning: 'The Light',                   description: 'The One who is the Light of the heavens and earth, guiding to truth.' },
  { number: 94, arabic: 'الْهَادِي',           transliteration: 'Al-Hadi',             meaning: 'The Guide',                   description: 'The One who guides His servants to what is good and beneficial.' },
  { number: 95, arabic: 'الْبَدِيع',           transliteration: "Al-Badi'",            meaning: 'The Originator',              description: 'The One who creates in a unique and unprecedented manner.' },
  { number: 96, arabic: 'الْبَاقِي',           transliteration: 'Al-Baqi',             meaning: 'The Everlasting',             description: 'The One whose existence has no end — He outlasts all of creation.' },
  { number: 97, arabic: 'الْوَارِث',           transliteration: 'Al-Warith',           meaning: 'The Inheritor',               description: 'The One who inherits everything after all creation has perished.' },
  { number: 98, arabic: 'الرَّشِيد',           transliteration: 'Ar-Rashid',           meaning: 'The Guide to the Right Path', description: 'The One who guides creation to what is correct and leads them to truth.' },
  { number: 99, arabic: 'الصَّبُور',           transliteration: 'As-Sabur',            meaning: 'The Patient',                 description: 'The One who is patient and does not hasten to punish those who disobey Him.' },
];
