export type DuaCategory =
  | 'morning' | 'evening' | 'sleep' | 'food'
  | 'prayer' | 'home' | 'travel' | 'distress'
  | 'forgiveness' | 'family';

export const DUA_CATEGORY_META: Record<DuaCategory, { label: string; icon: string; color: string }> = {
  morning:     { label: 'Morning',     icon: '🌅', color: '#E08A1A' },
  evening:     { label: 'Evening',     icon: '🌙', color: '#4A5BAF' },
  sleep:       { label: 'Sleep',       icon: '💤', color: '#7E5BB5' },
  food:        { label: 'Food',        icon: '🍽️',  color: '#3A9B5C' },
  prayer:      { label: 'Prayer',      icon: '🕌', color: '#C8780A' },
  home:        { label: 'Home',        icon: '🏠', color: '#D06020' },
  travel:      { label: 'Travel',      icon: '🚗', color: '#2A8BA8' },
  distress:    { label: 'Distress',    icon: '🤲', color: '#B84A4A' },
  forgiveness: { label: 'Forgiveness', icon: '💚', color: '#1A7A3C' },
  family:      { label: 'Family',      icon: '❤️',  color: '#C83A5A' },
};

export type Dua = {
  id: string;
  category: DuaCategory;
  title: string;
  arabic: string;
  transliteration: string;
  translation: string;
  reference: string;
};

export const DUAS: Dua[] = [
  // ─── MORNING ────────────────────────────────────────────────────────────────
  {
    id: 'morning_1',
    category: 'morning',
    title: 'Upon Waking Up',
    arabic: 'الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ',
    transliteration: 'Alhamdulillahil-lathee ahyana ba\'da ma amatana wa-ilayhin-nushoor',
    translation: 'All praise is for Allah who gave us life after having taken it from us and unto Him is the resurrection.',
    reference: 'Bukhari',
  },
  {
    id: 'morning_2',
    category: 'morning',
    title: 'Morning Remembrance (Sabah)',
    arabic: 'أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ',
    transliteration: 'Asbahna wa asbahal-mulku lillah, walhamdulillah, la ilaha illallahu wahdahu la shareeka lah, lahul-mulku walahul-hamd, wa huwa \'ala kulli shay\'in qadeer',
    translation: 'We have entered a new day and with it all dominion belongs to Allah. All praise is for Allah. None has the right to be worshipped except Allah, alone, without partner. To Him belongs all sovereignty and praise, and He is over all things omnipotent.',
    reference: 'Muslim',
  },
  {
    id: 'morning_3',
    category: 'morning',
    title: 'Morning Protection',
    arabic: 'اللَّهُمَّ بِكَ أَصْبَحْنَا، وَبِكَ أَمْسَيْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ النُّشُورُ',
    transliteration: 'Allahumma bika asbahna, wa bika amsayna, wa bika nahya, wa bika namootu, wa ilaykан-nushoor',
    translation: 'O Allah, by You we have entered the morning, by You we have entered the evening, by You we live, by You we die and to You is the resurrection.',
    reference: 'Abu Dawud, Tirmidhi',
  },
  {
    id: 'morning_4',
    category: 'morning',
    title: 'Morning Tasbih (100x)',
    arabic: 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ',
    transliteration: 'Subhanallahi wa bihamdih',
    translation: 'Glory be to Allah and all praise is due to Him.',
    reference: 'Bukhari, Muslim',
  },
  {
    id: 'morning_5',
    category: 'morning',
    title: 'Morning Complete Dhikr',
    arabic: 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنتَ، عَلَيْكَ تَوَكَّلْتُ، وَأَنتَ رَبُّ الْعَرْشِ الْعَظِيمِ',
    transliteration: 'Allahumma anta rabbee la ilaha illa ant, \'alayka tawakkaltu, wa anta rabbul-\'arshil-\'adheem',
    translation: 'O Allah, You are my Lord, none has the right to be worshipped except You. Upon You I rely and You are the Lord of the Mighty Throne.',
    reference: 'Abu Dawud',
  },

  // ─── EVENING ────────────────────────────────────────────────────────────────
  {
    id: 'evening_1',
    category: 'evening',
    title: 'Upon Entering Evening',
    arabic: 'أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ',
    transliteration: 'Amsayna wa amsal-mulku lillah, walhamdulillah, la ilaha illallahu wahdahu la shareeka lah',
    translation: 'We have entered the evening and with it all dominion belongs to Allah. All praise is for Allah. None has the right to be worshipped except Allah, alone, without partner.',
    reference: 'Muslim',
  },
  {
    id: 'evening_2',
    category: 'evening',
    title: 'Evening Protection',
    arabic: 'اللَّهُمَّ بِكَ أَمْسَيْنَا، وَبِكَ أَصْبَحْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ الْمَصِيرُ',
    transliteration: 'Allahumma bika amsayna, wa bika asbahna, wa bika nahya, wa bika namootu, wa ilaykal-maseer',
    translation: 'O Allah, by You we have entered the evening, by You we have entered the morning, by You we live, by You we die, and to You is the final return.',
    reference: 'Abu Dawud, Tirmidhi',
  },
  {
    id: 'evening_3',
    category: 'evening',
    title: 'Evening Istighfar (3x)',
    arabic: 'أَسْتَغْفِرُ اللَّهَ وَأَتُوبُ إِلَيْهِ',
    transliteration: 'Astaghfirullaha wa atoobu ilayh',
    translation: 'I seek the forgiveness of Allah and repent to Him.',
    reference: 'Bukhari, Muslim',
  },
  {
    id: 'evening_4',
    category: 'evening',
    title: 'Evening Seeking Refuge',
    arabic: 'أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ',
    transliteration: 'A\'udhu bikalimatillahit-tammati min sharri ma khalaq',
    translation: 'I seek refuge in the perfect words of Allah from the evil of what He has created.',
    reference: 'Muslim',
  },

  // ─── SLEEP ──────────────────────────────────────────────────────────────────
  {
    id: 'sleep_1',
    category: 'sleep',
    title: 'Before Going to Sleep',
    arabic: 'بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا',
    transliteration: 'Bismika Allahumma amootu wa ahya',
    translation: 'In Your name O Allah, I die and I live.',
    reference: 'Bukhari',
  },
  {
    id: 'sleep_2',
    category: 'sleep',
    title: 'Sleeping Dhikr (33x each)',
    arabic: 'سُبْحَانَ اللَّهِ ۝ الْحَمْدُ لِلَّهِ ۝ اللَّهُ أَكْبَرُ',
    transliteration: 'Subhanallah ۝ Alhamdulillah ۝ Allahu Akbar',
    translation: 'Glory be to Allah (33x) ۝ All praise is for Allah (33x) ۝ Allah is the Greatest (34x)',
    reference: 'Bukhari, Muslim',
  },
  {
    id: 'sleep_3',
    category: 'sleep',
    title: 'Sleeping Supplication',
    arabic: 'اللَّهُمَّ قِنِي عَذَابَكَ يَوْمَ تَبْعَثُ عِبَادَكَ',
    transliteration: 'Allahumma qinee \'adhabaka yawma tab\'athu \'ibadak',
    translation: 'O Allah, protect me from Your punishment on the day You resurrect Your servants.',
    reference: 'Abu Dawud, Tirmidhi',
  },
  {
    id: 'sleep_4',
    category: 'sleep',
    title: 'Upon Turning in Bed',
    arabic: 'لَا إِلَهَ إِلَّا اللَّهُ الْوَاحِدُ الْقَهَّارُ، رَبُّ السَّمَاوَاتِ وَالْأَرْضِ وَمَا بَيْنَهُمَا الْعَزِيزُ الْغَفَّارُ',
    transliteration: 'La ilaha illallahul-wahidul-qahhar, rabbus-samawati wal-ardi wa ma baynahuma al-\'azeezul-ghaffar',
    translation: 'There is no deity except Allah, the One, the Subduer, Lord of the heavens and earth and all between them, the Almighty, the All-Forgiving.',
    reference: 'Hakim',
  },

  // ─── FOOD ───────────────────────────────────────────────────────────────────
  {
    id: 'food_1',
    category: 'food',
    title: 'Before Eating',
    arabic: 'بِسْمِ اللَّهِ',
    transliteration: 'Bismillah',
    translation: 'In the name of Allah.',
    reference: 'Abu Dawud',
  },
  {
    id: 'food_2',
    category: 'food',
    title: 'If Forgot Bismillah',
    arabic: 'بِسْمِ اللَّهِ أَوَّلَهُ وَآخِرَهُ',
    transliteration: 'Bismillahi awwalahu wa akhirahu',
    translation: 'In the name of Allah at its beginning and at its end.',
    reference: 'Abu Dawud, Tirmidhi',
  },
  {
    id: 'food_3',
    category: 'food',
    title: 'After Eating',
    arabic: 'الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنَا وَسَقَانَا وَجَعَلَنَا مُسْلِمِينَ',
    transliteration: 'Alhamdulillahil-lathee at\'amana wasaqana waja\'alana Muslimeen',
    translation: 'All praise is for Allah who fed us and gave us drink and made us Muslims.',
    reference: 'Abu Dawud, Tirmidhi',
  },
  {
    id: 'food_4',
    category: 'food',
    title: 'After Eating (Complete)',
    arabic: 'الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَ وَسَقَى وَسَوَّغَهُ وَجَعَلَ لَهُ مَخْرَجًا',
    transliteration: 'Alhamdulillahil-lathee at\'ama wa saqa wa sawwaghhahu wa ja\'ala lahu makhraja',
    translation: 'All praise is for Allah who provided food and drink, made it palatable and gave it a way out.',
    reference: 'Abu Dawud',
  },
  {
    id: 'food_5',
    category: 'food',
    title: 'Before Drinking Water',
    arabic: 'بِسْمِ اللَّهِ',
    transliteration: 'Bismillah',
    translation: 'In the name of Allah.',
    reference: 'Tirmidhi',
  },
  {
    id: 'food_6',
    category: 'food',
    title: 'After Drinking Milk',
    arabic: 'اللَّهُمَّ بَارِكْ لَنَا فِيهِ وَزِدْنَا مِنْهُ',
    transliteration: 'Allahumma barik lana feehi wa zidna minhu',
    translation: 'O Allah, bless us in it and give us more of it.',
    reference: 'Abu Dawud, Tirmidhi',
  },

  // ─── PRAYER ─────────────────────────────────────────────────────────────────
  {
    id: 'prayer_1',
    category: 'prayer',
    title: 'Before Wudu',
    arabic: 'بِسْمِ اللَّهِ',
    transliteration: 'Bismillah',
    translation: 'In the name of Allah.',
    reference: 'Abu Dawud',
  },
  {
    id: 'prayer_2',
    category: 'prayer',
    title: 'After Wudu',
    arabic: 'أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، وَأَشْهَدُ أَنَّ مُحَمَّداً عَبْدُهُ وَرَسُولُهُ، اللَّهُمَّ اجْعَلْنِي مِنَ التَّوَّابِينَ وَاجْعَلْنِي مِنَ الْمُتَطَهِّرِينَ',
    transliteration: 'Ash-hadu an la ilaha illallahu wahdahu la shareeka lah, wa ash-hadu anna Muhammadan \'abduhu wa rasooluh. Allahumma-j\'alnee minat-tawwabeen waj\'alnee minal-mutatahhireen',
    translation: 'I bear witness that none has the right to be worshipped except Allah alone, without partner, and I bear witness that Muhammad is His slave and Messenger. O Allah, make me among those who return to You in repentance and make me among those who are purified.',
    reference: 'Muslim',
  },
  {
    id: 'prayer_3',
    category: 'prayer',
    title: 'Entering the Mosque',
    arabic: 'اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ',
    transliteration: 'Allahummaftah lee abwaba rahmatik',
    translation: 'O Allah, open the gates of Your mercy for me.',
    reference: 'Muslim',
  },
  {
    id: 'prayer_4',
    category: 'prayer',
    title: 'Leaving the Mosque',
    arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِكَ',
    transliteration: 'Allahumma innee as\'aluka min fadlik',
    translation: 'O Allah, I ask You from Your bounty.',
    reference: 'Muslim, Abu Dawud',
  },
  {
    id: 'prayer_5',
    category: 'prayer',
    title: 'At-Tahiyyat Opening',
    arabic: 'التَّحِيَّاتُ لِلَّهِ وَالصَّلَوَاتُ وَالطَّيِّبَاتُ، السَّلَامُ عَلَيْكَ أَيُّهَا النَّبِيُّ وَرَحْمَةُ اللَّهِ وَبَرَكَاتُهُ، السَّلَامُ عَلَيْنَا وَعَلَى عِبَادِ اللَّهِ الصَّالِحِينَ',
    transliteration: 'At-tahiyyatu lillahi was-salawatu wat-tayyibat, as-salamu \'alayka ayyuhan-nabiyyu wa rahmatullahi wa barakatuh, as-salamu \'alayna wa \'ala \'ibadillahis-saliheen',
    translation: 'All greetings, prayers, and good things are for Allah. Peace be upon you O Prophet, and the mercy of Allah and His blessings. Peace be upon us and upon the righteous servants of Allah.',
    reference: 'Bukhari, Muslim',
  },
  {
    id: 'prayer_6',
    category: 'prayer',
    title: 'Adhan Response',
    arabic: 'اللَّهُمَّ رَبَّ هَذِهِ الدَّعْوَةِ التَّامَّةِ وَالصَّلَاةِ الْقَائِمَةِ، آتِ مُحَمَّداً الْوَسِيلَةَ وَالْفَضِيلَةَ وَابْعَثْهُ مَقَاماً مَّحْمُوداً الَّذِي وَعَدْتَهُ',
    transliteration: 'Allahumma rabba hadhihid-da\'watit-tammah, was-salatil-qa\'imah, ati Muhammadanil-waseelata wal-fadeelah, wab\'ath-hu maqamam-mahmudanil-lathee wa\'adtah',
    translation: 'O Allah, Lord of this perfect call and established prayer, grant Muhammad the intercession and the favour, and raise him to the praised station that You have promised him.',
    reference: 'Bukhari',
  },

  // ─── HOME ───────────────────────────────────────────────────────────────────
  {
    id: 'home_1',
    category: 'home',
    title: 'Entering the Home',
    arabic: 'بِسْمِ اللَّهِ وَلَجْنَا وَبِسْمِ اللَّهِ خَرَجْنَا وَعَلَى اللَّهِ رَبِّنَا تَوَكَّلْنَا',
    transliteration: 'Bismillahi walajna, wa bismillahi kharajna, wa \'alallahi rabbina tawakkalna',
    translation: 'In the name of Allah we enter, in the name of Allah we leave, and upon our Lord we place our trust.',
    reference: 'Abu Dawud',
  },
  {
    id: 'home_2',
    category: 'home',
    title: 'Leaving the Home',
    arabic: 'بِسْمِ اللَّهِ تَوَكَّلْتُ عَلَى اللَّهِ، وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ',
    transliteration: 'Bismillah, tawakkaltu \'alallah, wa la hawla wa la quwwata illa billah',
    translation: 'In the name of Allah, I place my trust in Allah and there is no might nor power except with Allah.',
    reference: 'Abu Dawud, Tirmidhi',
  },
  {
    id: 'home_3',
    category: 'home',
    title: 'Entering the Toilet',
    arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْخُبُثِ وَالْخَبَائِثِ',
    transliteration: 'Allahumma innee a\'udhu bika minal-khubuthi wal-khaba\'ith',
    translation: 'O Allah, I seek refuge in You from male and female evil (jinn).',
    reference: 'Bukhari, Muslim',
  },
  {
    id: 'home_4',
    category: 'home',
    title: 'Leaving the Toilet',
    arabic: 'غُفْرَانَكَ',
    transliteration: 'Ghufranaka',
    translation: 'I seek Your forgiveness.',
    reference: 'Abu Dawud, Tirmidhi',
  },
  {
    id: 'home_5',
    category: 'home',
    title: 'Sneezing',
    arabic: 'الْحَمْدُ لِلَّهِ',
    transliteration: 'Alhamdulillah',
    translation: 'All praise is for Allah. (The one who hears replies: "Yarhamukallah" — May Allah have mercy on you. The sneezer then says: "Yahdikumullahu wa yuslihu balakum" — May Allah guide you and set your affairs in order.)',
    reference: 'Bukhari',
  },
  {
    id: 'home_6',
    category: 'home',
    title: 'Before Looking in the Mirror',
    arabic: 'اللَّهُمَّ أَنتَ حَسَّنْتَ خَلْقِي فَحَسِّنْ خُلُقِي',
    transliteration: 'Allahumma anta hassanta khalqee fahassin khuluqee',
    translation: 'O Allah, just as You have made my external appearance beautiful, make my character beautiful as well.',
    reference: 'Ahmad',
  },

  // ─── TRAVEL ─────────────────────────────────────────────────────────────────
  {
    id: 'travel_1',
    category: 'travel',
    title: 'Boarding a Vehicle',
    arabic: 'سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ وَإِنَّا إِلَى رَبِّنَا لَمُنقَلِبُونَ',
    transliteration: 'Subhanal-lathee sakhkhara lana hatha wama kunna lahu muqrineen. Wa inna ila rabbina lamunqaliboon',
    translation: 'Glory be to He who has subjected this to us, and we were not able to do it ourselves, and verily to our Lord we shall return.',
    reference: 'Abu Dawud, Tirmidhi',
  },
  {
    id: 'travel_2',
    category: 'travel',
    title: 'Dua for a Journey',
    arabic: 'اللَّهُمَّ إِنَّا نَسْأَلُكَ فِي سَفَرِنَا هَذَا الْبِرَّ وَالتَّقْوَى، وَمِنَ الْعَمَلِ مَا تَرْضَى',
    transliteration: 'Allahumma inna nas\'aluka fee safarina hatha al-birra wat-taqwa, wa minal-\'amali ma tarda',
    translation: 'O Allah, we ask You for righteousness and piety in this journey of ours, and for deeds that are pleasing to You.',
    reference: 'Muslim',
  },
  {
    id: 'travel_3',
    category: 'travel',
    title: 'Entering a New City',
    arabic: 'اللَّهُمَّ رَبَّ السَّمَاوَاتِ السَّبْعِ وَمَا أَظْلَلْنَ، وَرَبَّ الْأَرَضِينَ السَّبْعِ وَمَا أَقْلَلْنَ، أَسْأَلُكَ خَيْرَ هَذِهِ الْقَرْيَةِ وَخَيْرَ أَهْلِهَا',
    transliteration: 'Allahumma rabbas-samawatis-sab\'i wa ma adhallna, wa rabbal-aradinass-sab\'i wa ma aqlalna, as\'aluka khayra hadhihil-qaryati wa khayra ahlaha',
    translation: 'O Allah, Lord of the seven heavens and what they shade, Lord of the seven earths and what they hold, I ask You for the goodness of this town and the goodness of its people.',
    reference: 'Hakim',
  },
  {
    id: 'travel_4',
    category: 'travel',
    title: 'Returning from Travel',
    arabic: 'آيِبُونَ تَائِبُونَ عَابِدُونَ لِرَبِّنَا حَامِدُونَ',
    transliteration: 'Ayiboona ta\'iboona \'abiboona lirabbina hamidoon',
    translation: 'We return, repent, worship, and praise our Lord.',
    reference: 'Muslim',
  },

  // ─── DISTRESS ───────────────────────────────────────────────────────────────
  {
    id: 'distress_1',
    category: 'distress',
    title: 'Dua of Yunus (Prophet Jonah)',
    arabic: 'لَا إِلَهَ إِلَّا أَنتَ سُبْحَانَكَ إِنِّي كُنتُ مِنَ الظَّالِمِينَ',
    transliteration: 'La ilaha illa anta subhanaka innee kuntu minadh-dhalimeen',
    translation: 'There is no deity except You; exalted are You. Indeed, I have been of the wrongdoers.',
    reference: 'Quran 21:87',
  },
  {
    id: 'distress_2',
    category: 'distress',
    title: 'For Anxiety & Worry',
    arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ، وَأَعُوذُ بِكَ مِنَ الْعَجْزِ وَالْكَسَلِ، وَأَعُوذُ بِكَ مِنَ الْجُبْنِ وَالْبُخْلِ، وَأَعُوذُ بِكَ مِنْ غَلَبَةِ الدَّيْنِ وَقَهْرِ الرِّجَالِ',
    transliteration: 'Allahumma innee a\'udhu bika minal-hammi wal-hazan, wa a\'udhu bika minal-\'ajzi wal-kasal, wa a\'udhu bika minal-jubni wal-bukhl, wa a\'udhu bika min ghalabatid-dayni wa qahrir-rijal',
    translation: 'O Allah, I seek refuge in You from worry and grief, from incapacity and laziness, from cowardice and miserliness, and from the burden of debt and being overpowered by men.',
    reference: 'Bukhari',
  },
  {
    id: 'distress_3',
    category: 'distress',
    title: 'When Afflicted with Hardship',
    arabic: 'إِنَّا لِلَّهِ وَإِنَّا إِلَيْهِ رَاجِعُونَ، اللَّهُمَّ أْجُرْنِي فِي مُصِيبَتِي وَأَخْلِفْ لِي خَيْرًا مِنْهَا',
    transliteration: 'Inna lillahi wa inna ilayhi raji\'oon, Allahumma ajurnee fee museebatee wa akhlif lee khayran minha',
    translation: 'Verily we belong to Allah and verily to Him we shall return. O Allah, reward me in this affliction and replace it with something better.',
    reference: 'Muslim',
  },
  {
    id: 'distress_4',
    category: 'distress',
    title: 'Hasbiyallah (Reliance on Allah)',
    arabic: 'حَسْبِيَ اللَّهُ لَا إِلَهَ إِلَّا هُوَ، عَلَيْهِ تَوَكَّلْتُ وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ',
    transliteration: 'Hasbiyallahu la ilaha illa huwa, \'alayhi tawakkaltu wa huwa rabbul-\'arshil-\'adheem',
    translation: 'Allah is sufficient for me; there is no deity except Him. Upon Him I rely and He is the Lord of the Mighty Throne.',
    reference: 'Abu Dawud',
  },
  {
    id: 'distress_5',
    category: 'distress',
    title: 'For Relief from Distress',
    arabic: 'لَا إِلَهَ إِلَّا اللَّهُ الْعَظِيمُ الْحَلِيمُ، لَا إِلَهَ إِلَّا اللَّهُ رَبُّ الْعَرْشِ الْعَظِيمِ، لَا إِلَهَ إِلَّا اللَّهُ رَبُّ السَّمَاوَاتِ وَرَبُّ الْأَرْضِ وَرَبُّ الْعَرْشِ الْكَرِيمِ',
    transliteration: 'La ilaha illallahul-\'adhimul-haleem, la ilaha illallahu rabbul-\'arshil-\'adheem, la ilaha illallahu rabbus-samawati wa rabbul-ardi wa rabbul-\'arshil-kareem',
    translation: 'There is no deity except Allah, the Great, the Forbearing. There is no deity except Allah, Lord of the Mighty Throne. There is no deity except Allah, Lord of the heavens, Lord of the earth, and Lord of the Noble Throne.',
    reference: 'Bukhari, Muslim',
  },
  {
    id: 'distress_6',
    category: 'distress',
    title: 'When Feeling Overwhelmed',
    arabic: 'اللَّهُمَّ رَحْمَتَكَ أَرْجُو فَلَا تَكِلْنِي إِلَى نَفْسِي طَرْفَةَ عَيْنٍ، وَأَصْلِحْ لِي شَأْنِي كُلَّهُ',
    transliteration: 'Allahumma rahmataka arju fala takilnee ila nafsee tarfata \'ayn, wa aslih lee sha\'nee kullahu',
    translation: 'O Allah, it is Your mercy that I hope for, so do not leave me in charge of my affairs even for the blink of an eye, and rectify for me all of my affairs.',
    reference: 'Abu Dawud',
  },

  // ─── FORGIVENESS ────────────────────────────────────────────────────────────
  {
    id: 'forgiveness_1',
    category: 'forgiveness',
    title: 'Sayyidul Istighfar',
    arabic: 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنتَ',
    transliteration: 'Allahumma anta rabbee la ilaha illa ant, khalaqtanee wa ana \'abduk, wa ana \'ala \'ahdika wa wa\'dika mas-tata\'t, a\'udhu bika min sharri ma sana\'t, aboo\'u laka bini\'matika \'alayya wa aboo\'u bi-dhambee faghfir lee fa-innahu la yaghfirudh-dhunooba illa ant',
    translation: 'O Allah, You are my Lord, none has the right to be worshipped except You, You created me and I am Your servant, and I abide by Your covenant and promise as best I can. I seek refuge in You from the evil that I have done. I acknowledge Your blessings upon me and I confess my sins to You, so forgive me, for none forgives sins except You.',
    reference: 'Bukhari',
  },
  {
    id: 'forgiveness_2',
    category: 'forgiveness',
    title: 'Simple Istighfar',
    arabic: 'أَسْتَغْفِرُ اللَّهَ الْعَظِيمَ الَّذِي لَا إِلَهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ وَأَتُوبُ إِلَيْهِ',
    transliteration: 'Astaghfirullahil-\'adhimal-lathee la ilaha illa huwal-hayyul-qayyumu wa atoobu ilayh',
    translation: 'I seek forgiveness from Allah the Mighty, Whom there is no deity except Him, the Living, the Self-Sustaining, and I repent to Him.',
    reference: 'Abu Dawud, Tirmidhi',
  },
  {
    id: 'forgiveness_3',
    category: 'forgiveness',
    title: 'Tawbah (Repentance)',
    arabic: 'رَبَّنَا ظَلَمْنَا أَنفُسَنَا وَإِن لَّمْ تَغْفِرْ لَنَا وَتَرْحَمْنَا لَنَكُونَنَّ مِنَ الْخَاسِرِينَ',
    transliteration: 'Rabbana dhalamna anfusana wa in lam taghfir lana wa tarhamna lanakoonnanna minal-khasireen',
    translation: 'Our Lord, we have wronged ourselves, and if You do not forgive us and have mercy upon us, we will surely be among the losers.',
    reference: 'Quran 7:23',
  },
  {
    id: 'forgiveness_4',
    category: 'forgiveness',
    title: 'Dua of Prophet Ibrahim for Forgiveness',
    arabic: 'رَبِّ اغْفِرْ لِي وَلِوَالِدَيَّ وَلِلْمُؤْمِنِينَ يَوْمَ يَقُومُ الْحِسَابُ',
    transliteration: 'Rabbigh-fir lee wa liwalidayya wa lil-mu\'mineena yawma yaqumul-hisab',
    translation: 'My Lord, forgive me and my parents and the believers on the Day when the account is established.',
    reference: 'Quran 14:41',
  },

  // ─── FAMILY ─────────────────────────────────────────────────────────────────
  {
    id: 'family_1',
    category: 'family',
    title: 'For Parents',
    arabic: 'رَّبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا',
    transliteration: 'Rabbi irhamhuma kama rabbayani sagheera',
    translation: 'My Lord, have mercy upon them as they brought me up when I was small.',
    reference: 'Quran 17:24',
  },
  {
    id: 'family_2',
    category: 'family',
    title: 'For Righteous Children',
    arabic: 'رَبِّ هَبْ لِي مِن لَّدُنكَ ذُرِّيَّةً طَيِّبَةً ۖ إِنَّكَ سَمِيعُ الدُّعَاءِ',
    transliteration: 'Rabbi hab lee min ladunka dhurriyyatan tayyibah, innaka sami\'ud-du\'a\'',
    translation: 'My Lord, grant me from Yourself a good offspring. Indeed, You are the Hearer of supplication.',
    reference: 'Quran 3:38',
  },
  {
    id: 'family_3',
    category: 'family',
    title: 'For a Righteous Spouse & Family',
    arabic: 'رَبَّنَا هَبْ لَنَا مِنْ أَزْوَاجِنَا وَذُرِّيَّاتِنَا قُرَّةَ أَعْيُنٍ وَاجْعَلْنَا لِلْمُتَّقِينَ إِمَامًا',
    transliteration: 'Rabbana hab lana min azwajina wa dhurriyyatina qurrata a\'yunin waj\'alna lil-muttaqeena imama',
    translation: 'Our Lord, grant us from among our wives and offspring comfort to our eyes and make us a leader for the righteous.',
    reference: 'Quran 25:74',
  },
  {
    id: 'family_4',
    category: 'family',
    title: 'For Deceased Loved Ones',
    arabic: 'اللَّهُمَّ اغْفِرْ لَهُ وَارْحَمْهُ وَعَافِهِ وَاعْفُ عَنْهُ، وَأَكْرِمْ نُزُلَهُ وَوَسِّعْ مُدْخَلَهُ',
    transliteration: 'Allahummaghfir lahu warhamhu wa \'afihi wa\'fu \'anhu, wa akrim nuzulahu wa wassi\' mudkhalahu',
    translation: 'O Allah, forgive him, have mercy on him, give him strength, and pardon him. Honor his reception, and widen his entrance (into Paradise).',
    reference: 'Muslim',
  },
  {
    id: 'family_5',
    category: 'family',
    title: 'For the Sick',
    arabic: 'اللَّهُمَّ رَبَّ النَّاسِ، أَذْهِبِ الْبَأْسَ، اشْفِ أَنتَ الشَّافِي، لَا شِفَاءَ إِلَّا شِفَاؤُكَ، شِفَاءً لَا يُغَادِرُ سَقَمًا',
    transliteration: 'Allahumma rabban-nas, adh-hibil-ba\'s, washfi antash-shafi, la shifa\'a illa shifa\'uk, shifa\'an la yughadiru saqama',
    translation: 'O Allah, Lord of the people, remove the hardship, cure (him/her) for You are the Curer. There is no cure except Your cure, a cure that leaves no illness behind.',
    reference: 'Bukhari, Muslim',
  },
  {
    id: 'family_6',
    category: 'family',
    title: 'For a New Baby',
    arabic: 'بَارَكَ اللَّهُ لَكَ فِي الْمَوْهُوبِ لَكَ، وَشَكَرْتَ الْوَاهِبَ، وَبَلَغَ أَشُدَّهُ، وَرُزِقْتَ بِرَّهُ',
    transliteration: 'Barakallahu laka fil-mawhubi lak, wa shakarta al-wahib, wa balagha ashuddahu, wa ruziqta birrah',
    translation: 'May Allah bless you in this gift He has given you. May you give thanks to the Giver, may the child reach maturity, and may you be granted its righteousness.',
    reference: 'Ibn Sunni',
  },
];
