export type Hadith = {
  id: number;
  arabic: string;
  english: string;
  urdu: string;
  narrator: string;
  source: string;
};

export const HADITHS: Hadith[] = [
  {
    id: 1,
    arabic: 'إِنَّمَا الْأَعْمَالُ بِالنِّيَّاتِ',
    english: 'Actions are judged only by intentions, and every man shall have only that which he intended.',
    urdu: 'اعمال کا دار و مدار نیتوں پر ہے۔ ہر شخص کو وہی ملے گا جس کی اس نے نیت کی۔',
    narrator: 'Umar ibn al-Khattab',
    source: 'Bukhari 1, Muslim 1907',
  },
  {
    id: 2,
    arabic: 'خَيْرُكُمْ مَنْ تَعَلَّمَ الْقُرْآنَ وَعَلَّمَهُ',
    english: 'The best of you is the one who learns the Qur\'an and teaches it.',
    urdu: 'تم میں سے بہترین وہ ہے جو قرآن سیکھے اور سکھائے۔',
    narrator: 'Uthman ibn Affan',
    source: 'Bukhari 5027',
  },
  {
    id: 3,
    arabic: 'تَبَسُّمُكَ فِي وَجْهِ أَخِيكَ لَكَ صَدَقَةٌ',
    english: 'Your smile to your brother is a charity (sadaqah) for you.',
    urdu: 'اپنے بھائی کے چہرے پر مسکرانا بھی تمہارے لیے صدقہ ہے۔',
    narrator: 'Abu Dharr',
    source: 'Tirmidhi 1956 (hasan)',
  },
  {
    id: 4,
    arabic: 'الْمُسْلِمُ مَنْ سَلِمَ الْمُسْلِمُونَ مِنْ لِسَانِهِ وَيَدِهِ',
    english: 'The Muslim is the one from whose tongue and hand other Muslims are safe.',
    urdu: 'مسلمان وہ ہے جس کی زبان اور ہاتھ سے دوسرے مسلمان محفوظ رہیں۔',
    narrator: 'Abdullah ibn Amr',
    source: 'Bukhari 10, Muslim 40',
  },
  {
    id: 5,
    arabic: 'الطُّهُورُ شَطْرُ الْإِيمَانِ',
    english: 'Cleanliness is half of faith.',
    urdu: 'پاکیزگی نصف ایمان ہے۔',
    narrator: 'Abu Malik al-Ash\'ari',
    source: 'Muslim 223',
  },
  {
    id: 6,
    arabic: 'لَا يُؤْمِنُ أَحَدُكُمْ حَتَّى يُحِبَّ لِأَخِيهِ مَا يُحِبُّ لِنَفْسِهِ',
    english: 'None of you truly believes until he loves for his brother what he loves for himself.',
    urdu: 'تم میں سے کوئی شخص اس وقت تک مومن نہیں ہو سکتا جب تک اپنے بھائی کے لیے وہی نہ چاہے جو اپنے لیے چاہتا ہے۔',
    narrator: 'Anas ibn Malik',
    source: 'Bukhari 13, Muslim 45',
  },
  {
    id: 7,
    arabic: 'مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الْآخِرِ فَلْيَقُلْ خَيْرًا أَوْ لِيَصْمُتْ',
    english: 'Whoever believes in Allah and the Last Day, let him speak good or remain silent.',
    urdu: 'جو شخص اللہ اور آخرت کے دن پر ایمان رکھتا ہے، اسے چاہیے کہ اچھی بات کہے یا خاموش رہے۔',
    narrator: 'Abu Hurairah',
    source: 'Bukhari 6018, Muslim 47',
  },
  {
    id: 8,
    arabic: 'الرَّاحِمُونَ يَرْحَمُهُمُ الرَّحْمَنُ ارْحَمُوا مَنْ فِي الْأَرْضِ يَرْحَمْكُمْ مَنْ فِي السَّمَاءِ',
    english: 'The merciful are shown mercy by the Most Merciful. Show mercy to those on earth, and the One above the heavens will show mercy to you.',
    urdu: 'رحم کرنے والوں پر الرحمن رحم فرماتا ہے۔ تم زمین والوں پر رحم کرو، آسمان والا تم پر رحم فرمائے گا۔',
    narrator: 'Abdullah ibn Amr',
    source: 'Tirmidhi 1924 (sahih)',
  },
  {
    id: 9,
    arabic: 'مَنْ لَا يَشْكُرُ النَّاسَ لَا يَشْكُرُ اللَّهَ',
    english: 'Whoever does not thank people, does not thank Allah.',
    urdu: 'جو لوگوں کا شکر ادا نہیں کرتا، وہ اللہ کا شکر ادا نہیں کرتا۔',
    narrator: 'Abu Hurairah',
    source: 'Abu Dawud 4811 (sahih)',
  },
  {
    id: 10,
    arabic: 'لَا تَغْضَبْ',
    english: 'Do not get angry.',
    urdu: 'غصہ مت کرو۔',
    narrator: 'Abu Hurairah',
    source: 'Bukhari 6116',
  },
  {
    id: 11,
    arabic: 'أَحَبُّ الْأَعْمَالِ إِلَى اللَّهِ أَدْوَمُهَا وَإِنْ قَلَّ',
    english: 'The most beloved of deeds to Allah are those that are consistent, even if they are small.',
    urdu: 'اللہ کو سب سے زیادہ پسندیدہ عمل وہ ہے جو مستقل کیا جائے، چاہے کم ہی کیوں نہ ہو۔',
    narrator: 'Aisha',
    source: 'Bukhari 6464, Muslim 783',
  },
  {
    id: 12,
    arabic: 'الدُّعَاءُ هُوَ الْعِبَادَةُ',
    english: 'Supplication (dua) is worship.',
    urdu: 'دعا ہی عبادت ہے۔',
    narrator: 'Nu\'man ibn Bashir',
    source: 'Tirmidhi 2969 (sahih)',
  },
  {
    id: 13,
    arabic: 'مَنْ صَلَّى الْفَجْرَ فِي جَمَاعَةٍ فَهُوَ فِي ذِمَّةِ اللَّهِ',
    english: 'Whoever prays Fajr in congregation is under the protection of Allah.',
    urdu: 'جس نے فجر جماعت کے ساتھ پڑھی، وہ اللہ کی حفاظت میں ہے۔',
    narrator: 'Jundub ibn Abdillah',
    source: 'Muslim 657',
  },
  {
    id: 14,
    arabic: 'الْكَلِمَةُ الطَّيِّبَةُ صَدَقَةٌ',
    english: 'A good word is a charity.',
    urdu: 'اچھی بات بھی صدقہ ہے۔',
    narrator: 'Abu Hurairah',
    source: 'Bukhari 2989, Muslim 1009',
  },
  {
    id: 15,
    arabic: 'مَنْ سَتَرَ مُسْلِمًا سَتَرَهُ اللَّهُ يَوْمَ الْقِيَامَةِ',
    english: 'Whoever covers (the fault of) a Muslim, Allah will cover him on the Day of Resurrection.',
    urdu: 'جو کسی مسلمان کا عیب چھپائے، اللہ قیامت کے دن اس کا عیب چھپائے گا۔',
    narrator: 'Abdullah ibn Umar',
    source: 'Bukhari 2442, Muslim 2580',
  },
  {
    id: 16,
    arabic: 'إِنَّ اللَّهَ جَمِيلٌ يُحِبُّ الْجَمَالَ',
    english: 'Indeed Allah is beautiful and loves beauty.',
    urdu: 'بے شک اللہ خوبصورت ہے اور خوبصورتی کو پسند کرتا ہے۔',
    narrator: 'Abdullah ibn Mas\'ud',
    source: 'Muslim 91',
  },
  {
    id: 17,
    arabic: 'الْجَنَّةُ تَحْتَ أَقْدَامِ الْأُمَّهَاتِ',
    english: 'Paradise lies at the feet of mothers.',
    urdu: 'جنت ماؤں کے قدموں تلے ہے۔',
    narrator: 'Mu\'awiyah ibn Jahima',
    source: 'Nasa\'i 3104 (hasan)',
  },
  {
    id: 18,
    arabic: 'اسْتَعِنْ بِاللَّهِ وَلَا تَعْجَزْ',
    english: 'Seek help from Allah, and do not lose heart.',
    urdu: 'اللہ سے مدد مانگو اور ہمت نہ ہارو۔',
    narrator: 'Abu Hurairah',
    source: 'Muslim 2664',
  },
  {
    id: 19,
    arabic: 'لَا يَدْخُلُ الْجَنَّةَ مَنْ كَانَ فِي قَلْبِهِ مِثْقَالُ ذَرَّةٍ مِنْ كِبْرٍ',
    english: 'No one will enter Paradise who has an atom\'s weight of pride in his heart.',
    urdu: 'جس کے دل میں ذرہ برابر بھی تکبر ہو، وہ جنت میں داخل نہیں ہو گا۔',
    narrator: 'Abdullah ibn Mas\'ud',
    source: 'Muslim 91',
  },
  {
    id: 20,
    arabic: 'إِنَّ الرِّفْقَ لَا يَكُونُ فِي شَيْءٍ إِلَّا زَانَهُ',
    english: 'Gentleness is not found in anything except that it beautifies it.',
    urdu: 'نرمی جس چیز میں بھی ہو، اسے خوبصورت بنا دیتی ہے۔',
    narrator: 'Aisha',
    source: 'Muslim 2594',
  },
  {
    id: 21,
    arabic: 'الْمُؤْمِنُ الْقَوِيُّ خَيْرٌ وَأَحَبُّ إِلَى اللَّهِ مِنَ الْمُؤْمِنِ الضَّعِيفِ',
    english: 'The strong believer is better and more beloved to Allah than the weak believer — but there is good in both.',
    urdu: 'طاقتور مومن، کمزور مومن سے اللہ کو زیادہ محبوب اور بہتر ہے — اور دونوں میں خیر ہے۔',
    narrator: 'Abu Hurairah',
    source: 'Muslim 2664',
  },
  {
    id: 22,
    arabic: 'مَنْ يُرِدِ اللَّهُ بِهِ خَيْرًا يُفَقِّهْهُ فِي الدِّينِ',
    english: 'Whoever Allah wishes good for, He gives him understanding of the religion.',
    urdu: 'اللہ جس کے ساتھ بھلائی چاہتا ہے، اسے دین کی سمجھ عطا فرماتا ہے۔',
    narrator: 'Mu\'awiyah',
    source: 'Bukhari 71, Muslim 1037',
  },
  {
    id: 23,
    arabic: 'مَنْ صَمَتَ نَجَا',
    english: 'Whoever remains silent is saved.',
    urdu: 'جس نے خاموشی اختیار کی وہ نجات پا گیا۔',
    narrator: 'Abdullah ibn Amr',
    source: 'Tirmidhi 2501 (hasan)',
  },
  {
    id: 24,
    arabic: 'لَنْ يَشْبَعَ مُؤْمِنٌ مِنْ خَيْرٍ حَتَّى يَكُونَ مُنْتَهَاهُ الْجَنَّةَ',
    english: 'A believer is never satisfied with good until he reaches Paradise.',
    urdu: 'مومن بھلائی سے کبھی سیر نہیں ہوتا، یہاں تک کہ اس کا ٹھکانا جنت بن جائے۔',
    narrator: 'Abu Sa\'id al-Khudri',
    source: 'Tirmidhi 2686 (sahih)',
  },
  {
    id: 25,
    arabic: 'زَوِّجُوا الْأَيَامَى وَأَطْعِمُوا الطَّعَامَ',
    english: 'Help people marry, and feed the hungry.',
    urdu: 'بے نکاح لوگوں کے نکاح کراؤ اور کھانا کھلاؤ۔',
    narrator: 'Ibn Abbas',
    source: 'Abu Dawud (authentic)',
  },
  {
    id: 26,
    arabic: 'أَفْضَلُ الصَّدَقَةِ سَقْيُ الْمَاءِ',
    english: 'The best charity is to give water.',
    urdu: 'بہترین صدقہ پانی پلانا ہے۔',
    narrator: 'Sa\'d ibn Ubadah',
    source: 'Abu Dawud 1681, Nasa\'i 3664',
  },
  {
    id: 27,
    arabic: 'الصَّلَاةُ نُورٌ، وَالصَّدَقَةُ بُرْهَانٌ، وَالصَّبْرُ ضِيَاءٌ',
    english: 'Prayer is light, charity is proof, and patience is illumination.',
    urdu: 'نماز نور ہے، صدقہ دلیل ہے، اور صبر روشنی ہے۔',
    narrator: 'Abu Malik al-Ash\'ari',
    source: 'Muslim 223',
  },
  {
    id: 28,
    arabic: 'مَنْ لَمْ يَرْحَمْ صَغِيرَنَا وَيَعْرِفْ حَقَّ كَبِيرِنَا فَلَيْسَ مِنَّا',
    english: 'He who does not show mercy to our young and respect our elders is not one of us.',
    urdu: 'جو ہمارے چھوٹوں پر رحم نہ کرے اور بڑوں کا حق نہ پہچانے، وہ ہم میں سے نہیں۔',
    narrator: 'Abdullah ibn Amr',
    source: 'Tirmidhi 1920 (sahih)',
  },
  {
    id: 29,
    arabic: 'احْرِصْ عَلَى مَا يَنْفَعُكَ، وَاسْتَعِنْ بِاللَّهِ، وَلَا تَعْجَزْ',
    english: 'Be eager for what benefits you, seek Allah\'s help, and do not give up.',
    urdu: 'اس چیز کی خواہش رکھو جو تمہیں نفع دے، اللہ سے مدد مانگو، اور ہمت نہ ہارو۔',
    narrator: 'Abu Hurairah',
    source: 'Muslim 2664',
  },
  {
    id: 30,
    arabic: 'مَنْ تَوَكَّلَ عَلَى اللَّهِ فَهُوَ حَسْبُهُ',
    english: 'Whoever relies upon Allah — He is sufficient for him.',
    urdu: 'جو اللہ پر توکل کرے، اللہ اس کے لیے کافی ہے۔',
    narrator: 'Ibn Abbas',
    source: 'Qur\'an 65:3 (Divine Hadith context)',
  },
  {
    id: 31,
    arabic: 'مَنْ صَلَّى عَلَيَّ صَلَاةً صَلَّى اللَّهُ عَلَيْهِ بِهَا عَشْرًا',
    english: 'Whoever sends blessings upon me once, Allah sends blessings upon him ten times.',
    urdu: 'جو مجھ پر ایک بار درود بھیجتا ہے، اللہ اس پر دس بار رحمت نازل فرماتا ہے۔',
    narrator: 'Abu Hurairah',
    source: 'Muslim 408',
  },
  {
    id: 32,
    arabic: 'كَلِمَتَانِ خَفِيفَتَانِ عَلَى اللِّسَانِ ثَقِيلَتَانِ فِي الْمِيزَانِ: سُبْحَانَ اللَّهِ وَبِحَمْدِهِ، سُبْحَانَ اللَّهِ الْعَظِيمِ',
    english: 'Two phrases are light on the tongue, heavy on the scale, beloved to the Most Merciful: SubhanAllah wa bihamdihi, SubhanAllahil-Azeem.',
    urdu: 'دو کلمے زبان پر ہلکے، میزان میں بھاری اور رحمن کو محبوب ہیں: سبحان اللہ وبحمدہ، سبحان اللہ العظیم۔',
    narrator: 'Abu Hurairah',
    source: 'Bukhari 6406, Muslim 2694',
  },
  {
    id: 33,
    arabic: 'مَنْ قَالَ لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ مِائَةَ مَرَّةٍ',
    english: 'Whoever says "La ilaha illallah wahdahu la sharika lah…" one hundred times in a day, it is equivalent to freeing ten slaves.',
    urdu: 'جو روزانہ سو مرتبہ لا الہ الا اللہ وحدہ لا شریک لہ کہے، گویا اس نے دس غلام آزاد کیے۔',
    narrator: 'Abu Hurairah',
    source: 'Bukhari 3293, Muslim 2691',
  },
  {
    id: 34,
    arabic: 'مَنْ حَافَظَ عَلَى الصَّلَوَاتِ الْخَمْسِ كَانَتْ لَهُ نُورًا وَبُرْهَانًا وَنَجَاةً يَوْمَ الْقِيَامَةِ',
    english: 'Whoever guards the five daily prayers — they will be a light, proof, and salvation for him on the Day of Judgement.',
    urdu: 'جو پانچوں نمازوں کی حفاظت کرے، وہ قیامت کے دن اس کے لیے نور، دلیل اور نجات ہوں گی۔',
    narrator: 'Abdullah ibn Amr',
    source: 'Ahmad 6576, Ibn Hibban',
  },
  {
    id: 35,
    arabic: 'مَنْ قَرَأَ حَرْفًا مِنْ كِتَابِ اللَّهِ فَلَهُ بِهِ حَسَنَةٌ وَالْحَسَنَةُ بِعَشْرِ أَمْثَالِهَا',
    english: 'Whoever recites a single letter from the Book of Allah, he earns one good deed — and a good deed is multiplied by ten.',
    urdu: 'جو اللہ کی کتاب کا ایک حرف بھی پڑھے، اسے ایک نیکی ملتی ہے اور نیکی کا اجر دس گنا ہے۔',
    narrator: 'Abdullah ibn Mas\'ud',
    source: 'Tirmidhi 2910 (sahih)',
  },
  {
    id: 36,
    arabic: 'مَنْ قَالَ سُبْحَانَ اللَّهِ وَبِحَمْدِهِ فِي يَوْمٍ مِائَةَ مَرَّةٍ حُطَّتْ خَطَايَاهُ',
    english: 'Whoever says "SubhanAllahi wa bihamdihi" one hundred times a day, his sins are wiped away, even if they were like the foam of the sea.',
    urdu: 'جو دن میں سو مرتبہ سبحان اللہ وبحمدہ کہے، اس کے گناہ معاف کر دیے جاتے ہیں، چاہے سمندر کی جھاگ کے برابر ہوں۔',
    narrator: 'Abu Hurairah',
    source: 'Bukhari 6405, Muslim 2691',
  },
  {
    id: 37,
    arabic: 'الدِّينُ النَّصِيحَةُ',
    english: 'The religion is sincere counsel.',
    urdu: 'دین خیر خواہی کا نام ہے۔',
    narrator: 'Tamim al-Dari',
    source: 'Muslim 55',
  },
  {
    id: 38,
    arabic: 'لَا يَشْكُرُ النَّاسَ مَنْ لَا يَشْكُرُ اللَّهَ',
    english: 'He who does not thank Allah does not thank people.',
    urdu: 'جو اللہ کا شکر نہیں کرتا وہ لوگوں کا بھی شکر نہیں کرتا۔',
    narrator: 'Abu Hurairah',
    source: 'Ahmad, Abu Dawud 4811',
  },
  {
    id: 39,
    arabic: 'مَنْ سَلَكَ طَرِيقًا يَلْتَمِسُ فِيهِ عِلْمًا سَهَّلَ اللَّهُ لَهُ بِهِ طَرِيقًا إِلَى الْجَنَّةِ',
    english: 'Whoever takes a path in search of knowledge, Allah makes easy for him a path to Paradise.',
    urdu: 'جو علم کی تلاش میں کوئی راستہ اختیار کرتا ہے، اللہ اس کے لیے جنت کا راستہ آسان کر دیتا ہے۔',
    narrator: 'Abu Hurairah',
    source: 'Muslim 2699',
  },
  {
    id: 40,
    arabic: 'مَنْ صَامَ رَمَضَانَ إِيمَانًا وَاحْتِسَابًا غُفِرَ لَهُ مَا تَقَدَّمَ مِنْ ذَنْبِهِ',
    english: 'Whoever fasts Ramadan out of faith and seeking reward, his previous sins are forgiven.',
    urdu: 'جس نے ایمان اور ثواب کی نیت سے رمضان کے روزے رکھے، اس کے گزشتہ گناہ معاف کر دیے گئے۔',
    narrator: 'Abu Hurairah',
    source: 'Bukhari 38, Muslim 760',
  },
  {
    id: 41,
    arabic: 'مَنْ قَامَ لَيْلَةَ الْقَدْرِ إِيمَانًا وَاحْتِسَابًا غُفِرَ لَهُ مَا تَقَدَّمَ مِنْ ذَنْبِهِ',
    english: 'Whoever stands in prayer on Laylatul Qadr out of faith and hope for reward, his previous sins will be forgiven.',
    urdu: 'جو ایمان اور ثواب کی نیت سے شبِ قدر میں قیام کرے، اس کے گزشتہ گناہ معاف ہو جاتے ہیں۔',
    narrator: 'Abu Hurairah',
    source: 'Bukhari 1901, Muslim 760',
  },
  {
    id: 42,
    arabic: 'خَيْرُ النَّاسِ أَنْفَعُهُمْ لِلنَّاسِ',
    english: 'The best of people are those who are most beneficial to people.',
    urdu: 'لوگوں میں سب سے بہتر وہ ہے جو لوگوں کو سب سے زیادہ نفع پہنچائے۔',
    narrator: 'Jabir ibn Abdullah',
    source: 'Al-Mu\'jam al-Awsat (hasan)',
  },
  {
    id: 43,
    arabic: 'لَا ضَرَرَ وَلَا ضِرَارَ',
    english: 'There should be no harm, nor reciprocating harm.',
    urdu: 'نہ نقصان پہنچاؤ اور نہ بدلے میں نقصان۔',
    narrator: 'Ibn Abbas',
    source: 'Ibn Majah 2341 (hasan)',
  },
  {
    id: 44,
    arabic: 'إِذَا مَاتَ ابْنُ آدَمَ انْقَطَعَ عَمَلُهُ إِلَّا مِنْ ثَلَاثٍ: صَدَقَةٍ جَارِيَةٍ، أَوْ عِلْمٍ يُنْتَفَعُ بِهِ، أَوْ وَلَدٍ صَالِحٍ يَدْعُو لَهُ',
    english: 'When a person dies, his deeds end except three: ongoing charity, beneficial knowledge, or a righteous child who prays for him.',
    urdu: 'جب انسان مر جاتا ہے تو اس کا عمل ختم ہو جاتا ہے سوائے تین چیزوں کے: صدقہ جاریہ، نفع بخش علم، اور نیک اولاد جو اس کے لیے دعا کرے۔',
    narrator: 'Abu Hurairah',
    source: 'Muslim 1631',
  },
  {
    id: 45,
    arabic: 'مَنْ كَانَ فِي حَاجَةِ أَخِيهِ كَانَ اللَّهُ فِي حَاجَتِهِ',
    english: 'Whoever helps his brother, Allah will help him.',
    urdu: 'جو اپنے بھائی کی حاجت پوری کرتا ہے، اللہ اس کی حاجت پوری فرماتا ہے۔',
    narrator: 'Abdullah ibn Umar',
    source: 'Bukhari 2442, Muslim 2580',
  },
  {
    id: 46,
    arabic: 'أَقْرَبُ مَا يَكُونُ الْعَبْدُ مِنْ رَبِّهِ وَهُوَ سَاجِدٌ',
    english: 'The closest a servant is to his Lord is while he is in prostration.',
    urdu: 'بندہ اپنے رب کے سب سے قریب اُس وقت ہوتا ہے جب وہ سجدے میں ہو۔',
    narrator: 'Abu Hurairah',
    source: 'Muslim 482',
  },
  {
    id: 47,
    arabic: 'مَا نَقَصَتْ صَدَقَةٌ مِنْ مَالٍ',
    english: 'Charity does not decrease wealth.',
    urdu: 'صدقہ مال کو کم نہیں کرتا۔',
    narrator: 'Abu Hurairah',
    source: 'Muslim 2588',
  },
  {
    id: 48,
    arabic: 'الصَّلَاةُ عَلَى وَقْتِهَا',
    english: 'The most beloved deed to Allah is prayer at its proper time.',
    urdu: 'اللہ کو سب سے محبوب عمل وقت پر نماز ادا کرنا ہے۔',
    narrator: 'Abdullah ibn Mas\'ud',
    source: 'Bukhari 527, Muslim 85',
  },
  {
    id: 49,
    arabic: 'اتَّقِ اللَّهَ حَيْثُمَا كُنْتَ، وَأَتْبِعِ السَّيِّئَةَ الْحَسَنَةَ تَمْحُهَا، وَخَالِقِ النَّاسَ بِخُلُقٍ حَسَنٍ',
    english: 'Fear Allah wherever you are, follow a bad deed with a good one to erase it, and treat people with good character.',
    urdu: 'جہاں بھی ہو اللہ سے ڈرو، برائی کے بعد نیکی کرو تاکہ وہ مٹ جائے، اور لوگوں کے ساتھ اچھے اخلاق سے پیش آؤ۔',
    narrator: 'Abu Dharr',
    source: 'Tirmidhi 1987 (hasan)',
  },
  {
    id: 50,
    arabic: 'مَنْ ذَهَبَ إِلَى الْمَسْجِدِ وَرَاحَ أَعَدَّ اللَّهُ لَهُ نُزُلَهُ مِنَ الْجَنَّةِ كُلَّمَا غَدَا أَوْ رَاحَ',
    english: 'Whoever goes to the mosque morning and evening, Allah prepares for him a place in Paradise each time he goes and returns.',
    urdu: 'جو مسجد آتا جاتا ہے، اللہ اس کے لیے ہر آنے جانے پر جنت میں مہمانی تیار فرماتا ہے۔',
    narrator: 'Abu Hurairah',
    source: 'Bukhari 662, Muslim 669',
  },
  {
    id: 51,
    arabic: 'الْمُؤْمِنُ لِلْمُؤْمِنِ كَالْبُنْيَانِ يَشُدُّ بَعْضُهُ بَعْضًا',
    english: 'A believer to another believer is like a building — each part strengthening the other.',
    urdu: 'ایک مومن دوسرے مومن کے لیے عمارت کی طرح ہے، جس کا ایک حصہ دوسرے کو مضبوط کرتا ہے۔',
    narrator: 'Abu Musa al-Ash\'ari',
    source: 'Bukhari 481, Muslim 2585',
  },
  {
    id: 52,
    arabic: 'رَغِمَ أَنْفُ ثُمَّ رَغِمَ أَنْفُ ثُمَّ رَغِمَ أَنْفُ مَنْ أَدْرَكَ أَبَوَيْهِ عِنْدَ الْكِبَرِ أَحَدَهُمَا أَوْ كِلَيْهِمَا ثُمَّ لَمْ يَدْخُلِ الْجَنَّةَ',
    english: 'May he be disgraced — whoever reaches his parents in old age, one or both of them, and does not enter Paradise (through their service).',
    urdu: 'ذلیل ہو وہ شخص جس نے والدین کو بڑھاپے میں پایا — ایک یا دونوں کو — اور پھر بھی جنت میں داخل نہ ہوا۔',
    narrator: 'Abu Hurairah',
    source: 'Muslim 2551',
  },
  {
    id: 53,
    arabic: 'مَنْ قَالَ حِينَ يُصْبِحُ وَحِينَ يُمْسِي: سُبْحَانَ اللَّهِ وَبِحَمْدِهِ مِائَةَ مَرَّةٍ لَمْ يَأْتِ أَحَدٌ يَوْمَ الْقِيَامَةِ بِأَفْضَلَ مِمَّا جَاءَ بِهِ',
    english: 'Whoever says "SubhanAllahi wa bihamdihi" 100 times morning and evening will not be surpassed on the Day of Judgement except by one who said the same or more.',
    urdu: 'جو صبح و شام سو مرتبہ سبحان اللہ وبحمدہ کہے، قیامت کے دن اس سے بہتر کوئی چیز لے کر نہیں آئے گا سوائے اس کے جس نے اسی کی مثل یا زیادہ کہی ہو۔',
    narrator: 'Abu Hurairah',
    source: 'Muslim 2692',
  },
  {
    id: 54,
    arabic: 'إِنَّ مِنْ أَحَبِّكُمْ إِلَيَّ وَأَقْرَبِكُمْ مِنِّي مَجْلِسًا يَوْمَ الْقِيَامَةِ أَحَاسِنَكُمْ أَخْلَاقًا',
    english: 'The most beloved and nearest to me on the Day of Judgement are those of you with the best character.',
    urdu: 'تم میں سے قیامت کے دن مجھے سب سے محبوب اور میرے قریب بیٹھنے والا وہ ہے جس کے اخلاق سب سے اچھے ہیں۔',
    narrator: 'Jabir ibn Abdullah',
    source: 'Tirmidhi 2018 (hasan)',
  },
  {
    id: 55,
    arabic: 'مَنْ كَظَمَ غَيْظًا وَهُوَ قَادِرٌ عَلَى أَنْ يُنْفِذَهُ دَعَاهُ اللَّهُ يَوْمَ الْقِيَامَةِ عَلَى رُءُوسِ الْخَلَائِقِ',
    english: 'Whoever suppresses his anger while being able to act on it, Allah will call him before all creation on the Day of Judgement to choose any maiden of Paradise he wishes.',
    urdu: 'جو غصے پر قابو پا لے باوجود اس کے کہ وہ اسے پورا کر سکتا ہے، اللہ اسے قیامت کے دن تمام مخلوق کے سامنے بلائے گا۔',
    narrator: 'Mu\'adh ibn Anas',
    source: 'Tirmidhi 2021 (hasan)',
  },
  {
    id: 56,
    arabic: 'نِعْمَتَانِ مَغْبُونٌ فِيهِمَا كَثِيرٌ مِنَ النَّاسِ: الصِّحَّةُ وَالْفَرَاغُ',
    english: 'Two blessings in which many people are deceived: health and free time.',
    urdu: 'دو نعمتوں میں اکثر لوگ دھوکے میں رہتے ہیں: صحت اور فراغت۔',
    narrator: 'Ibn Abbas',
    source: 'Bukhari 6412',
  },
  {
    id: 57,
    arabic: 'الطَّعَامُ طَعَامُ اثْنَيْنِ كَافِي الثَّلَاثَةَ، وَطَعَامُ الثَّلَاثَةِ كَافِي الْأَرْبَعَةَ',
    english: 'Food for two is enough for three, and food for three is enough for four.',
    urdu: 'دو کا کھانا تین کے لیے، اور تین کا کھانا چار کے لیے کافی ہے۔',
    narrator: 'Abu Hurairah',
    source: 'Bukhari 5392, Muslim 2058',
  },
  {
    id: 58,
    arabic: 'إِنَّ اللَّهَ يُحِبُّ إِذَا عَمِلَ أَحَدُكُمْ عَمَلًا أَنْ يُتْقِنَهُ',
    english: 'Allah loves when any of you does a task, that he does it with excellence.',
    urdu: 'اللہ پسند کرتا ہے کہ جب تم میں سے کوئی کام کرے تو اسے اچھی طرح انجام دے۔',
    narrator: 'Aisha',
    source: 'Al-Bayhaqi (hasan)',
  },
  {
    id: 59,
    arabic: 'الْكَيِّسُ مَنْ دَانَ نَفْسَهُ وَعَمِلَ لِمَا بَعْدَ الْمَوْتِ',
    english: 'The wise is the one who holds himself accountable and works for what comes after death.',
    urdu: 'عقلمند وہ ہے جو اپنے آپ کا محاسبہ کرے اور موت کے بعد کے لیے عمل کرے۔',
    narrator: 'Shaddad ibn Aws',
    source: 'Tirmidhi 2459 (hasan)',
  },
  {
    id: 60,
    arabic: 'لَا يَدْخُلُ الْجَنَّةَ قَتَّاتٌ',
    english: 'A tale-carrier (gossiper) will not enter Paradise.',
    urdu: 'چغل خور جنت میں داخل نہ ہوگا۔',
    narrator: 'Hudhayfah',
    source: 'Bukhari 6056, Muslim 105',
  },
  {
    id: 61,
    arabic: 'عَجِبْتُ لِأَمْرِ الْمُؤْمِنِ إِنَّ أَمْرَهُ كُلَّهُ خَيْرٌ',
    english: 'Amazing is the affair of the believer — all of it is good for him. If good befalls him, he is grateful; if harm, he is patient — both are good for him.',
    urdu: 'مومن کا معاملہ عجیب ہے — اس کا سارا معاملہ اس کے لیے بہتر ہے۔ خوشی ملے تو شکر، تکلیف ہو تو صبر — دونوں ہی اس کے لیے خیر ہیں۔',
    narrator: 'Suhayb ibn Sinan',
    source: 'Muslim 2999',
  },
  {
    id: 62,
    arabic: 'ادْعُوا اللَّهَ وَأَنْتُمْ مُوقِنُونَ بِالْإِجَابَةِ',
    english: 'Call on Allah while being certain He will answer.',
    urdu: 'اللہ سے دعا کرو یقین رکھتے ہوئے کہ وہ قبول فرمائے گا۔',
    narrator: 'Abu Hurairah',
    source: 'Tirmidhi 3479 (hasan)',
  },
  {
    id: 63,
    arabic: 'مَنْ غَسَّلَ يَوْمَ الْجُمُعَةِ وَاغْتَسَلَ ثُمَّ بَكَّرَ وَابْتَكَرَ',
    english: 'Whoever performs ghusl on Friday, comes early, listens attentively to the khutbah — for every step he takes, he gets the reward of a year of fasting and praying.',
    urdu: 'جو جمعہ کے دن غسل کرے، جلدی مسجد جائے اور خطبہ غور سے سنے، اس کے ہر قدم پر ایک سال کے روزوں اور نمازوں کا ثواب ہے۔',
    narrator: 'Aws ibn Aws',
    source: 'Abu Dawud 345 (sahih)',
  },
  {
    id: 64,
    arabic: 'مَنْ قَرَأَ آيَةَ الْكُرْسِيِّ دُبُرَ كُلِّ صَلَاةٍ مَكْتُوبَةٍ لَمْ يَمْنَعْهُ مِنْ دُخُولِ الْجَنَّةِ إِلَّا أَنْ يَمُوتَ',
    english: 'Whoever recites Ayat al-Kursi after every obligatory prayer, nothing stands between him and Paradise except death.',
    urdu: 'جو ہر فرض نماز کے بعد آیت الکرسی پڑھے، اس کے اور جنت کے درمیان صرف موت حائل ہے۔',
    narrator: 'Abu Umamah',
    source: 'Nasa\'i (hasan)',
  },
  {
    id: 65,
    arabic: 'رَكْعَتَا الْفَجْرِ خَيْرٌ مِنَ الدُّنْيَا وَمَا فِيهَا',
    english: 'The two rak\'ahs of Fajr (sunnah) are better than the world and all that it contains.',
    urdu: 'فجر کی دو رکعت (سنت) دنیا اور اس کی تمام چیزوں سے بہتر ہیں۔',
    narrator: 'Aisha',
    source: 'Muslim 725',
  },
  {
    id: 66,
    arabic: 'يَسِّرُوا وَلَا تُعَسِّرُوا، وَبَشِّرُوا وَلَا تُنَفِّرُوا',
    english: 'Make things easy and do not make them difficult. Give glad tidings and do not drive people away.',
    urdu: 'آسانی کرو، مشکل مت کرو۔ خوشخبری دو اور نفرت نہ پھیلاؤ۔',
    narrator: 'Anas ibn Malik',
    source: 'Bukhari 69, Muslim 1734',
  },
  {
    id: 67,
    arabic: 'خَيْرُ النَّاسِ مَنْ طَالَ عُمُرُهُ وَحَسُنَ عَمَلُهُ',
    english: 'The best of people is the one whose life is long and whose deeds are good.',
    urdu: 'لوگوں میں بہترین وہ ہے جس کی عمر لمبی ہو اور اعمال اچھے ہوں۔',
    narrator: 'Abdullah ibn Bishr',
    source: 'Tirmidhi 2330 (sahih)',
  },
  {
    id: 68,
    arabic: 'مَنْ صَلَّى الْبَرْدَيْنِ دَخَلَ الْجَنَّةَ',
    english: 'Whoever prays the two cool prayers (Fajr and Asr) will enter Paradise.',
    urdu: 'جو دو ٹھنڈی نمازیں (فجر اور عصر) ادا کرے، وہ جنت میں داخل ہوگا۔',
    narrator: 'Abu Musa al-Ash\'ari',
    source: 'Bukhari 574, Muslim 635',
  },
  {
    id: 69,
    arabic: 'الْمُسْلِمُ أَخُو الْمُسْلِمِ لَا يَظْلِمُهُ وَلَا يُسْلِمُهُ',
    english: 'A Muslim is the brother of another Muslim — he does not oppress him, nor does he abandon him.',
    urdu: 'مسلمان مسلمان کا بھائی ہے — نہ اس پر ظلم کرتا ہے نہ اسے چھوڑتا ہے۔',
    narrator: 'Abdullah ibn Umar',
    source: 'Bukhari 2442, Muslim 2580',
  },
  {
    id: 70,
    arabic: 'طَلَبُ الْعِلْمِ فَرِيضَةٌ عَلَى كُلِّ مُسْلِمٍ',
    english: 'Seeking knowledge is an obligation upon every Muslim.',
    urdu: 'علم کا حاصل کرنا ہر مسلمان پر فرض ہے۔',
    narrator: 'Anas ibn Malik',
    source: 'Ibn Majah 224 (sahih li ghayrihi)',
  },
  {
    id: 71,
    arabic: 'الْحَيَاءُ لَا يَأْتِي إِلَّا بِخَيْرٍ',
    english: 'Modesty brings nothing but good.',
    urdu: 'حیا سے خیر ہی آتی ہے۔',
    narrator: 'Imran ibn Husayn',
    source: 'Bukhari 6117, Muslim 37',
  },
  {
    id: 72,
    arabic: 'مَنْ بَنَى لِلَّهِ مَسْجِدًا بَنَى اللَّهُ لَهُ بَيْتًا فِي الْجَنَّةِ',
    english: 'Whoever builds a mosque for Allah, Allah will build a house for him in Paradise.',
    urdu: 'جو اللہ کے لیے مسجد بنائے، اللہ اس کے لیے جنت میں گھر بناتا ہے۔',
    narrator: 'Uthman ibn Affan',
    source: 'Bukhari 450, Muslim 533',
  },
  {
    id: 73,
    arabic: 'الْيَدُ الْعُلْيَا خَيْرٌ مِنَ الْيَدِ السُّفْلَى',
    english: 'The upper hand (giving) is better than the lower hand (receiving).',
    urdu: 'اوپر والا (دینے والا) ہاتھ نیچے والے (لینے والے) سے بہتر ہے۔',
    narrator: 'Abdullah ibn Umar',
    source: 'Bukhari 1429, Muslim 1033',
  },
  {
    id: 74,
    arabic: 'مَنْ غَرَسَ غَرْسًا فَأَكَلَ مِنْهُ إِنْسَانٌ أَوْ دَابَّةٌ إِلَّا كَانَ لَهُ صَدَقَةٌ',
    english: 'No Muslim plants a tree or sows a crop from which a person, bird, or animal eats except that it becomes a charity for him.',
    urdu: 'جو مسلمان درخت لگائے یا کھیتی کرے اور اس سے انسان، پرندہ یا جانور کھائے تو وہ اس کے لیے صدقہ بن جاتا ہے۔',
    narrator: 'Anas ibn Malik',
    source: 'Bukhari 2320, Muslim 1553',
  },
  {
    id: 75,
    arabic: 'مَنْ أَحْيَا لَيْلَةَ الْعِيدَيْنِ لَمْ يَمُتْ قَلْبُهُ يَوْمَ تَمُوتُ الْقُلُوبُ',
    english: 'Whoever strives to benefit from good deeds on the night of Eid, his heart will not die on the day hearts die.',
    urdu: 'جو عیدین کی راتیں عبادت میں گزارے، اس کا دل اس دن نہیں مرے گا جب دل مرتے ہیں۔',
    narrator: 'Abu Umamah',
    source: 'Ibn Majah 1782 (hasan)',
  },
  {
    id: 76,
    arabic: 'مَا مِنْ مُسْلِمٍ يَدْعُو بِدَعْوَةٍ لَيْسَ فِيهَا إِثْمٌ وَلَا قَطِيعَةُ رَحِمٍ إِلَّا أَعْطَاهُ اللَّهُ بِهَا إِحْدَى ثَلَاثٍ',
    english: 'No Muslim makes a dua free from sin or severing of kinship except Allah gives him one of three: answers it, delays it for a greater reward, or protects him from a harm equal to it.',
    urdu: 'کوئی مسلمان ایسی دعا نہیں کرتا جس میں گناہ یا قطع رحمی نہ ہو مگر اللہ اسے تین میں سے ایک عطا فرماتا ہے: اسے قبول کرتا ہے، آخرت کے لیے ذخیرہ کرتا ہے، یا ویسا ہی شر اس سے دور کر دیتا ہے۔',
    narrator: 'Abu Sa\'id al-Khudri',
    source: 'Ahmad 11133 (hasan)',
  },
  {
    id: 77,
    arabic: 'إِنَّ اللَّهَ لَا يَنْظُرُ إِلَى أَجْسَادِكُمْ وَلَا إِلَى صُوَرِكُمْ وَلَكِنْ يَنْظُرُ إِلَى قُلُوبِكُمْ',
    english: 'Allah does not look at your bodies or your faces, but He looks at your hearts and your deeds.',
    urdu: 'اللہ تمہاری صورتوں اور جسموں کو نہیں دیکھتا، بلکہ وہ تمہارے دلوں اور اعمال کو دیکھتا ہے۔',
    narrator: 'Abu Hurairah',
    source: 'Muslim 2564',
  },
  {
    id: 78,
    arabic: 'مَنْ كَذَبَ عَلَيَّ مُتَعَمِّدًا فَلْيَتَبَوَّأْ مَقْعَدَهُ مِنَ النَّارِ',
    english: 'Whoever deliberately lies about me, let him take his seat in the Fire.',
    urdu: 'جو جان بوجھ کر مجھ پر جھوٹ باندھے، وہ اپنا ٹھکانا جہنم میں بنا لے۔',
    narrator: 'Ali ibn Abi Talib',
    source: 'Bukhari 110, Muslim 3',
  },
  {
    id: 79,
    arabic: 'مَنْ يَرِدِ اللَّهُ بِهِ خَيْرًا يُصِبْ مِنْهُ',
    english: 'When Allah wants good for someone, He tests him.',
    urdu: 'اللہ جس کے ساتھ بھلائی چاہتا ہے، اسے آزمائش میں ڈالتا ہے۔',
    narrator: 'Abu Hurairah',
    source: 'Bukhari 5645',
  },
  {
    id: 80,
    arabic: 'إِنَّ الْمُؤْمِنَ لَيُدْرِكُ بِحُسْنِ خُلُقِهِ دَرَجَةَ الصَّائِمِ الْقَائِمِ',
    english: 'The believer, through good character, attains the rank of one who fasts by day and stands in prayer by night.',
    urdu: 'مومن اپنے اچھے اخلاق سے اس شخص کا درجہ پالیتا ہے جو دن کو روزہ رکھتا اور رات کو قیام کرتا ہے۔',
    narrator: 'Aisha',
    source: 'Abu Dawud 4798 (sahih)',
  },
  {
    id: 81,
    arabic: 'لَا تَحْقِرَنَّ مِنَ الْمَعْرُوفِ شَيْئًا وَلَوْ أَنْ تَلْقَى أَخَاكَ بِوَجْهٍ طَلْقٍ',
    english: 'Do not belittle any good deed, even meeting your brother with a cheerful face.',
    urdu: 'کسی بھی نیکی کو حقیر نہ سمجھو، چاہے وہ اپنے بھائی سے خندہ پیشانی سے ملنا ہی کیوں نہ ہو۔',
    narrator: 'Abu Dharr',
    source: 'Muslim 2626',
  },
  {
    id: 82,
    arabic: 'سَبَقَ الْمُفَرِّدُونَ. قَالُوا: وَمَا الْمُفَرِّدُونَ؟ قَالَ: الذَّاكِرُونَ اللَّهَ كَثِيرًا وَالذَّاكِرَاتُ',
    english: 'The Mufarridun have gone ahead. They asked: Who are the Mufarridun? He said: The men and women who remember Allah much.',
    urdu: 'مفردون سبقت لے گئے۔ صحابہ نے پوچھا: مفردون کون ہیں؟ فرمایا: وہ مرد اور عورتیں جو اللہ کا بہت ذکر کرتے ہیں۔',
    narrator: 'Abu Hurairah',
    source: 'Muslim 2676',
  },
  {
    id: 83,
    arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ الْهُدَى وَالتُّقَى وَالْعَفَافَ وَالْغِنَى',
    english: 'O Allah, I ask You for guidance, piety, chastity, and self-sufficiency.',
    urdu: 'اے اللہ! میں تجھ سے ہدایت، تقویٰ، پاکدامنی اور مال داری کا سوال کرتا ہوں۔',
    narrator: 'Abdullah ibn Mas\'ud',
    source: 'Muslim 2721',
  },
  {
    id: 84,
    arabic: 'خَيْرُكُمْ خَيْرُكُمْ لِأَهْلِهِ وَأَنَا خَيْرُكُمْ لِأَهْلِي',
    english: 'The best of you is the one who is best to his family — and I am the best of you to my family.',
    urdu: 'تم میں سے بہترین وہ ہے جو اپنے گھر والوں کے لیے بہترین ہے، اور میں تم سب میں اپنے گھر والوں کے لیے بہترین ہوں۔',
    narrator: 'Aisha',
    source: 'Tirmidhi 3895 (sahih)',
  },
  {
    id: 85,
    arabic: 'إِنَّ لِكُلِّ شَيْءٍ قَلْبًا وَقَلْبُ الْقُرْآنِ يس',
    english: 'Everything has a heart, and the heart of the Qur\'an is Surah Yaseen.',
    urdu: 'ہر چیز کا ایک دل ہے، اور قرآن کا دل سورۃ یٰسین ہے۔',
    narrator: 'Anas ibn Malik',
    source: 'Tirmidhi 2887 (da\'if but oft-cited)',
  },
  {
    id: 86,
    arabic: 'بَلِّغُوا عَنِّي وَلَوْ آيَةً',
    english: 'Convey from me, even if it is a single verse.',
    urdu: 'میری طرف سے لوگوں کو پہنچاؤ، اگرچہ ایک آیت ہی کیوں نہ ہو۔',
    narrator: 'Abdullah ibn Amr',
    source: 'Bukhari 3461',
  },
  {
    id: 87,
    arabic: 'لَا يَرْحَمُ اللَّهُ مَنْ لَا يَرْحَمُ النَّاسَ',
    english: 'Allah does not show mercy to those who do not show mercy to people.',
    urdu: 'جو لوگوں پر رحم نہیں کرتا، اللہ بھی اس پر رحم نہیں کرتا۔',
    narrator: 'Jarir ibn Abdullah',
    source: 'Bukhari 7376, Muslim 2319',
  },
  {
    id: 88,
    arabic: 'أَحَبُّ الْبِلَادِ إِلَى اللَّهِ مَسَاجِدُهَا، وَأَبْغَضُ الْبِلَادِ إِلَى اللَّهِ أَسْوَاقُهَا',
    english: 'The most beloved places to Allah are the mosques, and the most disliked places to Allah are the markets.',
    urdu: 'اللہ کو سب سے محبوب جگہیں مسجدیں ہیں، اور سب سے ناپسندیدہ جگہیں بازار۔',
    narrator: 'Abu Hurairah',
    source: 'Muslim 671',
  },
  {
    id: 89,
    arabic: 'مَنْ قَالَ حِينَ يُصْبِحُ وَحِينَ يُمْسِي: حَسْبِيَ اللَّهُ لَا إِلَهَ إِلَّا هُوَ عَلَيْهِ تَوَكَّلْتُ',
    english: 'Whoever says morning and evening "HasbiyAllah la ilaha illa Huwa, alayhi tawakkaltu…" seven times, Allah suffices him from all his worries.',
    urdu: 'جو صبح و شام سات مرتبہ "حسبی اللہ لا الہ الا ہو علیہ توکلت" کہے، اللہ اس کی تمام پریشانیوں کے لیے کافی ہو جاتا ہے۔',
    narrator: 'Abu Dardaa',
    source: 'Abu Dawud 5081',
  },
  {
    id: 90,
    arabic: 'لَا تَدْخُلُوا الْجَنَّةَ حَتَّى تُؤْمِنُوا، وَلَا تُؤْمِنُوا حَتَّى تَحَابُّوا. أَوَلَا أَدُلُّكُمْ عَلَى شَيْءٍ إِذَا فَعَلْتُمُوهُ تَحَابَبْتُمْ؟ أَفْشُوا السَّلَامَ بَيْنَكُمْ',
    english: 'You will not enter Paradise until you believe, and you will not believe until you love one another. Shall I tell you something that, if you do, you will love each other? Spread salaam among yourselves.',
    urdu: 'تم جنت میں داخل نہ ہو گے جب تک ایمان نہ لاؤ، اور ایمان نہ لاؤ گے جب تک آپس میں محبت نہ کرو۔ کیا میں تمہیں وہ بات بتاؤں جسے کرنے سے تم محبت کرنے لگو گے؟ آپس میں سلام کو پھیلاؤ۔',
    narrator: 'Abu Hurairah',
    source: 'Muslim 54',
  },
];

export function getDailyHadith(): Hadith {
  const start = new Date(2025, 0, 1).getTime();
  const now = new Date();
  now.setHours(0, 0, 0, 0);
  const daysSince = Math.floor((now.getTime() - start) / (1000 * 60 * 60 * 24));
  return HADITHS[Math.abs(daysSince) % HADITHS.length];
}
