export const MOTIVATIONAL_QUOTES = [
  { text: 'Verily, with hardship comes ease.', source: 'Quran 94:6' },
  { text: 'Do not lose hope, nor be sad.', source: 'Quran 3:139' },
  { text: 'And whoever relies upon Allah — then He is sufficient for him.', source: 'Quran 65:3' },
  { text: 'Your Lord has not abandoned you, nor has He become displeased.', source: 'Quran 93:3' },
  { text: 'Indeed, Allah is with the patient.', source: 'Quran 2:153' },
  { text: 'He knows what is in every heart.', source: 'Quran 67:13' },
  { text: 'So which of the favors of your Lord would you deny?', source: 'Quran 55:13' },
  { text: 'Allah does not burden a soul beyond that it can bear.', source: 'Quran 2:286' },
  { text: 'Call upon Me; I will respond to you.', source: 'Quran 40:60' },
  { text: 'And He found you lost and guided you.', source: 'Quran 93:7' },
  { text: 'Unquestionably, to Allah belongs whatever is in the heavens and the earth.', source: 'Quran 10:55' },
  { text: 'Indeed it is only in the remembrance of Allah that hearts find rest.', source: 'Quran 13:28' },
  { text: 'We are closer to him than his jugular vein.', source: 'Quran 50:16' },
  { text: 'And give good tidings to the patient.', source: 'Quran 2:155' },
  { text: 'Whoever fears Allah, He will make a way out for him.', source: 'Quran 65:2' },
  { text: 'He is with you wherever you are.', source: 'Quran 57:4' },
  { text: 'Allah is the ally of those who believe.', source: 'Quran 2:257' },
  { text: 'After every darkness there is light.', source: 'Islamic wisdom' },
  { text: 'The strong person is not the one who can overpower others. The strong person is the one who controls themselves when angry.', source: 'Prophet ﷺ' },
  { text: 'Make things easy, do not make them hard. Give good news and do not drive people away.', source: 'Prophet ﷺ' },
  { text: 'The best among you is the one who learns the Quran and teaches it.', source: 'Prophet ﷺ' },
  { text: 'Be in this world as if you were a stranger or a traveler.', source: 'Prophet ﷺ' },
  { text: 'Tie your camel, then put your trust in Allah.', source: 'Prophet ﷺ' },
  { text: 'Take up good deeds only as much as you are able, for the best deeds are those done regularly even if they are few.', source: 'Prophet ﷺ' },
  { text: 'None of you truly believes until he wishes for his brother what he wishes for himself.', source: 'Prophet ﷺ' },
  { text: 'Cleanliness is half of faith.', source: 'Prophet ﷺ' },
  { text: 'A good word is charity.', source: 'Prophet ﷺ' },
  { text: 'Smiling at your brother is charity.', source: 'Prophet ﷺ' },
  { text: 'The worldly life is a prison for the believer and a paradise for the disbeliever.', source: 'Prophet ﷺ' },
  { text: 'Whoever is kind, Allah will be kind to him.', source: 'Prophet ﷺ' },
  { text: 'Dua is the weapon of the believer.', source: 'Prophet ﷺ (reported in Mustadrak al-Hakim)' },
  { text: 'Patience is a pillar of faith.', source: 'Islamic wisdom' },
  { text: 'The heart that beats for Allah is always in a state of peace.', source: 'Islamic wisdom' },
  { text: 'The dunya is a shadow — do not build your home in a shadow.', source: 'Ibn Qayyim' },
  { text: 'Whoever knows himself knows his Lord.', source: 'Islamic wisdom' },
  { text: 'Rush towards prayer like you rush towards what you love.', source: 'Islamic wisdom' },
  { text: 'The wound is where the light enters.', source: 'Rumi' },
  { text: 'Live in this world like rain — pure, gentle, and life-giving.', source: 'Islamic wisdom' },
  { text: 'Grieve not. Whatever you lost in life was never yours to keep. Whatever remains is still a gift.', source: 'Islamic wisdom' },
  { text: 'And when My servants ask you concerning Me, indeed I am near.', source: 'Quran 2:186' },
  { text: 'Allah does not change the condition of a people until they change what is in themselves.', source: 'Quran 13:11' },
  { text: 'Say: My Lord, increase me in knowledge.', source: 'Quran 20:114' },
  { text: 'Indeed, the mercy of Allah is near to the doers of good.', source: 'Quran 7:56' },
  { text: 'Seek help through patience and prayer.', source: 'Quran 2:45' },
  { text: 'And never lose hope of relief from Allah.', source: 'Quran 12:87' },
  { text: 'He taught man that which he knew not.', source: 'Quran 96:5' },
  { text: 'Our Lord, give us in this world good and in the Hereafter good, and protect us from the punishment of the Fire.', source: 'Quran 2:201' },
  { text: 'My Lord! Expand for me my breast, and ease for me my task.', source: 'Quran 20:25-26' },
  { text: 'And whoever puts their trust in Allah — then He is sufficient for them.', source: 'Quran 65:3' },
  { text: 'Indeed Allah is with the patient.', source: 'Quran 8:46' },
  { text: 'My success is only by Allah.', source: 'Quran 11:88' },
  { text: 'And seek forgiveness of Allah. Indeed, Allah is ever Forgiving and Merciful.', source: 'Quran 4:106' },
  { text: 'Say: "Nothing will happen to us except what Allah has decreed for us."', source: 'Quran 9:51' },
  { text: 'Do not despair of the mercy of Allah. Indeed, Allah forgives all sins.', source: 'Quran 39:53' },
  { text: 'Verily in the remembrance of Allah do hearts find rest.', source: 'Quran 13:28' },
  { text: 'So remember Me; I will remember you.', source: 'Quran 2:152' },
  { text: 'Whoever fears Allah — He will make for him a way out.', source: 'Quran 65:2' },
  { text: 'And He will provide for him from where he does not expect.', source: 'Quran 65:3' },
  { text: 'The mercy of My Lord encompasses all things.', source: 'Quran 7:156' },
  { text: 'Indeed, Allah loves those who act justly.', source: 'Quran 49:9' },
  { text: 'Allah is the best of planners.', source: 'Quran 3:54' },
  { text: 'Say: O My servants who have transgressed against themselves — do not despair of the mercy of Allah.', source: 'Quran 39:53' },
  { text: 'And we have made the night as a covering, and made the day for livelihood.', source: 'Quran 78:10-11' },
  { text: 'Whatever good befalls you is from Allah.', source: 'Quran 4:79' },
  { text: 'Then which of the favors of your Lord will you deny?', source: 'Quran 55 (repeated)' },
  { text: 'Is the reward for good anything but good?', source: 'Quran 55:60' },
  { text: 'Indeed Allah loves those who rely upon Him.', source: 'Quran 3:159' },
  { text: 'And say: My Lord, I seek refuge in You from the suggestions of the devils.', source: 'Quran 23:97' },
  { text: 'My Lord, forgive me and grant me from You a kingdom such as will not belong to anyone after me.', source: 'Quran 38:35' },
  { text: 'Allah is pleased with them and they are pleased with Him.', source: 'Quran 5:119' },
  { text: 'And Allah is the best of providers.', source: 'Quran 62:11' },
  { text: 'Indeed, Allah will not allow to be lost the reward of those who do good.', source: 'Quran 9:120' },
  { text: 'Whoever does righteousness, whether male or female, while he is a believer — We will surely cause him to live a good life.', source: 'Quran 16:97' },
  { text: 'And to Allah belongs the dominion of the heavens and the earth.', source: 'Quran 45:27' },
  { text: 'Whoever relieves a believer\'s distress in this world, Allah will relieve his distress on the Day of Judgement.', source: 'Prophet ﷺ — Muslim 2699' },
  { text: 'A strong person is not one who overpowers others — the strong person controls himself when angry.', source: 'Prophet ﷺ — Bukhari 6114' },
  { text: 'Religion is ease — whoever overburdens himself in religion will be defeated by it.', source: 'Prophet ﷺ — Bukhari 39' },
  { text: 'Whoever believes in Allah and the Last Day should speak good or remain silent.', source: 'Prophet ﷺ — Bukhari 6018' },
  { text: 'The best among you are those who have the best manners and character.', source: 'Prophet ﷺ — Bukhari 3559' },
  { text: 'Actions are judged by intentions — every person will have what they intended.', source: 'Prophet ﷺ — Bukhari 1' },
  { text: 'Whoever takes a path in search of knowledge, Allah will make easy for him a path to Paradise.', source: 'Prophet ﷺ — Muslim 2699' },
  { text: 'The most beloved deeds to Allah are those done consistently, even if small.', source: 'Prophet ﷺ — Bukhari 6464' },
  { text: 'Richness is not abundance of wealth — real richness is the richness of the soul.', source: 'Prophet ﷺ — Bukhari 6446' },
  { text: 'A good word is charity.', source: 'Prophet ﷺ — Bukhari 2989' },
  { text: 'He who shows mercy will be shown mercy.', source: 'Prophet ﷺ — Bukhari 7376' },
  { text: 'Leave what makes you doubt for what does not make you doubt.', source: 'Prophet ﷺ — Tirmidhi 2518' },
  { text: 'Whoever is kind to Allah\'s creation, Allah is kind to him.', source: 'Prophet ﷺ — Abu Dawud' },
  { text: 'Kindness is not found in anything except that it beautifies it, and is never removed from anything except that it disgraces it.', source: 'Prophet ﷺ — Muslim 2594' },
  { text: 'Paradise lies at the feet of mothers.', source: 'Prophet ﷺ — Nasa\'i 3104' },
  { text: 'Modesty brings nothing but good.', source: 'Prophet ﷺ — Bukhari 6117' },
  { text: 'The closest a servant is to his Lord is when in prostration — so increase your dua there.', source: 'Prophet ﷺ — Muslim 482' },
  { text: 'Every act of goodness is charity.', source: 'Prophet ﷺ — Muslim 1005' },
  { text: 'The pleasure of Allah lies in the pleasure of the parents.', source: 'Prophet ﷺ — Tirmidhi 1899' },
  { text: 'Whoever guides someone to do good has the reward equal to one who does it.', source: 'Prophet ﷺ — Muslim 1893' },
  { text: 'None of you truly believes until his desires follow what I have brought.', source: 'Prophet ﷺ' },
  { text: 'Your Lord is embarrassed to turn away the hands raised to Him empty.', source: 'Prophet ﷺ — Abu Dawud 1488' },
  { text: 'Two rak\'ahs at the middle of the night are better than the world and all that is in it.', source: 'Prophet ﷺ (in meaning)' },
  { text: 'The believer\'s prayer is never rejected, it is either answered, delayed, or a harm is prevented from him.', source: 'Prophet ﷺ — Ahmad 11133' },
  { text: 'The shade of the Throne on the Day of Judgement is for seven — the youth who grew up worshipping Allah is one of them.', source: 'Prophet ﷺ — Bukhari 660' },
  { text: 'Take advantage of five before five: youth before old age, health before sickness, wealth before poverty, free time before preoccupation, life before death.', source: 'Prophet ﷺ — Al-Hakim' },
  { text: 'Do not belittle any act of kindness, even meeting your brother with a smile.', source: 'Prophet ﷺ — Muslim 2626' },
  { text: 'The world is a prison for the believer and a paradise for the disbeliever.', source: 'Prophet ﷺ — Muslim 2956' },
  { text: 'When one of you loves his brother, let him tell him.', source: 'Prophet ﷺ — Abu Dawud 5124' },
  { text: 'Verily Allah is gentle and loves gentleness in all matters.', source: 'Prophet ﷺ — Bukhari 6927' },
  { text: 'Smiling at your brother is charity.', source: 'Prophet ﷺ — Tirmidhi 1956' },
  { text: 'Each soul is responsible for what it has earned.', source: 'Quran 74:38' },
  { text: 'He who has patience with difficulty reaches great heights.', source: 'Islamic wisdom' },
  { text: 'Seek knowledge from the cradle to the grave.', source: 'Islamic wisdom' },
  { text: 'The ink of the scholar is more sacred than the blood of the martyr.', source: 'Islamic wisdom' },
  { text: 'A moment of patience in a moment of anger saves a thousand moments of regret.', source: 'Ali ibn Abi Talib (RA)' },
  { text: 'Do not let your difficulties fill you with anxiety; after all, it is only in the darkest nights that stars shine more brightly.', source: 'Ali ibn Abi Talib (RA)' },
  { text: 'The greatest wealth is contentment. The greatest poverty is greed.', source: 'Islamic wisdom' },
  { text: 'When you close your doors and think yourself alone, remember — you are never alone; Allah is there.', source: 'Islamic wisdom' },
  { text: 'Do not walk through the world looking for offenses — they will find you soon enough.', source: 'Islamic wisdom' },
  { text: 'Your heart is a garden — plant mercy, water it with dua, and harvest peace.', source: 'Islamic wisdom' },
  { text: 'Forgive people for the same reason you want to be forgiven by Allah.', source: 'Islamic wisdom' },
  { text: 'Dunya is a test — jannah is the reward. Never trade eternal for temporary.', source: 'Islamic wisdom' },
  { text: 'If your heart is restless, return to Allah. He is home.', source: 'Islamic wisdom' },
  { text: 'The best response to cruelty is dua. The best response to ignorance is silence.', source: 'Islamic wisdom' },
  { text: 'Allah loves those who repent often, even if they sin often.', source: 'Islamic wisdom' },
  { text: 'Every sunrise is a chance Allah gives you to start fresh.', source: 'Islamic wisdom' },
  { text: 'You are not behind. You are exactly where Allah placed you — now do your best from here.', source: 'Islamic wisdom' },
  { text: 'What is meant for you will not pass you — and what passes you was never meant for you.', source: 'Islamic wisdom' },
  { text: 'The heart that remembers Allah is the heart that finds peace in every storm.', source: 'Islamic wisdom' },
  { text: 'Pray before your prayer becomes your only regret.', source: 'Islamic wisdom' },
  { text: 'Consistency, not intensity, is what pleases Allah most.', source: 'Islamic wisdom' },
  { text: 'Your tears in sujood water seeds only Allah can see.', source: 'Islamic wisdom' },
];

export type QuoteEntry = { text: string; source: string };

export function getRandomQuote(): QuoteEntry {
  return MOTIVATIONAL_QUOTES[
    Math.floor(Math.random() * MOTIVATIONAL_QUOTES.length)
  ];
}
