export type SurahMeta = {
  number: number;
  nameArabic: string;
  nameEnglish: string;
  nameUrdu: string;
  meaning: string;
  ayahs: number;
  revelationType: 'Meccan' | 'Medinan';
};

export const SURAH_LIST: SurahMeta[] = [
  { number: 1, nameArabic: 'الفاتحة', nameEnglish: 'Al-Fatihah', nameUrdu: 'الفاتحہ', meaning: 'The Opening', ayahs: 7, revelationType: 'Meccan' },
  { number: 2, nameArabic: 'البقرة', nameEnglish: 'Al-Baqarah', nameUrdu: 'البقرہ', meaning: 'The Cow', ayahs: 286, revelationType: 'Medinan' },
  { number: 3, nameArabic: 'آل عمران', nameEnglish: "Ali 'Imran", nameUrdu: 'آل عمران', meaning: 'The Family of Imran', ayahs: 200, revelationType: 'Medinan' },
  { number: 4, nameArabic: 'النساء', nameEnglish: 'An-Nisa', nameUrdu: 'النساء', meaning: 'The Women', ayahs: 176, revelationType: 'Medinan' },
  { number: 5, nameArabic: 'المائدة', nameEnglish: 'Al-Maidah', nameUrdu: 'المائدہ', meaning: 'The Table Spread', ayahs: 120, revelationType: 'Medinan' },
  { number: 6, nameArabic: 'الأنعام', nameEnglish: "Al-An'am", nameUrdu: 'الانعام', meaning: 'The Cattle', ayahs: 165, revelationType: 'Meccan' },
  { number: 7, nameArabic: 'الأعراف', nameEnglish: "Al-A'raf", nameUrdu: 'الاعراف', meaning: 'The Heights', ayahs: 206, revelationType: 'Meccan' },
  { number: 8, nameArabic: 'الأنفال', nameEnglish: 'Al-Anfal', nameUrdu: 'الانفال', meaning: 'The Spoils of War', ayahs: 75, revelationType: 'Medinan' },
  { number: 9, nameArabic: 'التوبة', nameEnglish: 'At-Tawbah', nameUrdu: 'التوبہ', meaning: 'The Repentance', ayahs: 129, revelationType: 'Medinan' },
  { number: 10, nameArabic: 'يونس', nameEnglish: 'Yunus', nameUrdu: 'یونس', meaning: 'Jonah', ayahs: 109, revelationType: 'Meccan' },
  { number: 11, nameArabic: 'هود', nameEnglish: 'Hud', nameUrdu: 'ہود', meaning: 'Hud', ayahs: 123, revelationType: 'Meccan' },
  { number: 12, nameArabic: 'يوسف', nameEnglish: 'Yusuf', nameUrdu: 'یوسف', meaning: 'Joseph', ayahs: 111, revelationType: 'Meccan' },
  { number: 13, nameArabic: 'الرعد', nameEnglish: "Ar-Ra'd", nameUrdu: 'الرعد', meaning: 'The Thunder', ayahs: 43, revelationType: 'Medinan' },
  { number: 14, nameArabic: 'إبراهيم', nameEnglish: 'Ibrahim', nameUrdu: 'ابراہیم', meaning: 'Abraham', ayahs: 52, revelationType: 'Meccan' },
  { number: 15, nameArabic: 'الحجر', nameEnglish: 'Al-Hijr', nameUrdu: 'الحجر', meaning: 'The Rocky Tract', ayahs: 99, revelationType: 'Meccan' },
  { number: 16, nameArabic: 'النحل', nameEnglish: 'An-Nahl', nameUrdu: 'النحل', meaning: 'The Bee', ayahs: 128, revelationType: 'Meccan' },
  { number: 17, nameArabic: 'الإسراء', nameEnglish: "Al-Isra'", nameUrdu: 'الاسراء', meaning: 'The Night Journey', ayahs: 111, revelationType: 'Meccan' },
  { number: 18, nameArabic: 'الكهف', nameEnglish: 'Al-Kahf', nameUrdu: 'الکہف', meaning: 'The Cave', ayahs: 110, revelationType: 'Meccan' },
  { number: 19, nameArabic: 'مريم', nameEnglish: 'Maryam', nameUrdu: 'مریم', meaning: 'Mary', ayahs: 98, revelationType: 'Meccan' },
  { number: 20, nameArabic: 'طه', nameEnglish: 'Ta-Ha', nameUrdu: 'طٰہٰ', meaning: 'Ta-Ha', ayahs: 135, revelationType: 'Meccan' },
  { number: 21, nameArabic: 'الأنبياء', nameEnglish: "Al-Anbiya'", nameUrdu: 'الانبیاء', meaning: 'The Prophets', ayahs: 112, revelationType: 'Meccan' },
  { number: 22, nameArabic: 'الحج', nameEnglish: 'Al-Hajj', nameUrdu: 'الحج', meaning: 'The Pilgrimage', ayahs: 78, revelationType: 'Medinan' },
  { number: 23, nameArabic: 'المؤمنون', nameEnglish: "Al-Mu'minun", nameUrdu: 'المومنون', meaning: 'The Believers', ayahs: 118, revelationType: 'Meccan' },
  { number: 24, nameArabic: 'النور', nameEnglish: 'An-Nur', nameUrdu: 'النور', meaning: 'The Light', ayahs: 64, revelationType: 'Medinan' },
  { number: 25, nameArabic: 'الفرقان', nameEnglish: 'Al-Furqan', nameUrdu: 'الفرقان', meaning: 'The Criterion', ayahs: 77, revelationType: 'Meccan' },
  { number: 26, nameArabic: 'الشعراء', nameEnglish: "Ash-Shu'ara'", nameUrdu: 'الشعراء', meaning: 'The Poets', ayahs: 227, revelationType: 'Meccan' },
  { number: 27, nameArabic: 'النمل', nameEnglish: 'An-Naml', nameUrdu: 'النمل', meaning: 'The Ant', ayahs: 93, revelationType: 'Meccan' },
  { number: 28, nameArabic: 'القصص', nameEnglish: 'Al-Qasas', nameUrdu: 'القصص', meaning: 'The Stories', ayahs: 88, revelationType: 'Meccan' },
  { number: 29, nameArabic: 'العنكبوت', nameEnglish: 'Al-Ankabut', nameUrdu: 'العنکبوت', meaning: 'The Spider', ayahs: 69, revelationType: 'Meccan' },
  { number: 30, nameArabic: 'الروم', nameEnglish: 'Ar-Rum', nameUrdu: 'الروم', meaning: 'The Romans', ayahs: 60, revelationType: 'Meccan' },
  { number: 31, nameArabic: 'لقمان', nameEnglish: 'Luqman', nameUrdu: 'لقمان', meaning: 'Luqman', ayahs: 34, revelationType: 'Meccan' },
  { number: 32, nameArabic: 'السجدة', nameEnglish: 'As-Sajdah', nameUrdu: 'السجدہ', meaning: 'The Prostration', ayahs: 30, revelationType: 'Meccan' },
  { number: 33, nameArabic: 'الأحزاب', nameEnglish: 'Al-Ahzab', nameUrdu: 'الاحزاب', meaning: 'The Combined Forces', ayahs: 73, revelationType: 'Medinan' },
  { number: 34, nameArabic: 'سبأ', nameEnglish: 'Saba', nameUrdu: 'سبا', meaning: "Sheba", ayahs: 54, revelationType: 'Meccan' },
  { number: 35, nameArabic: 'فاطر', nameEnglish: 'Fatir', nameUrdu: 'فاطر', meaning: 'Originator', ayahs: 45, revelationType: 'Meccan' },
  { number: 36, nameArabic: 'يس', nameEnglish: 'Ya-Sin', nameUrdu: 'یٰسٓ', meaning: 'Ya Sin', ayahs: 83, revelationType: 'Meccan' },
  { number: 37, nameArabic: 'الصافات', nameEnglish: 'As-Saffat', nameUrdu: 'الصافات', meaning: 'Those Who Set The Ranks', ayahs: 182, revelationType: 'Meccan' },
  { number: 38, nameArabic: 'ص', nameEnglish: 'Sad', nameUrdu: 'ص', meaning: 'The Letter Sad', ayahs: 88, revelationType: 'Meccan' },
  { number: 39, nameArabic: 'الزمر', nameEnglish: 'Az-Zumar', nameUrdu: 'الزمر', meaning: 'The Troops', ayahs: 75, revelationType: 'Meccan' },
  { number: 40, nameArabic: 'غافر', nameEnglish: 'Ghafir', nameUrdu: 'غافر', meaning: 'The Forgiver', ayahs: 85, revelationType: 'Meccan' },
  { number: 41, nameArabic: 'فصلت', nameEnglish: 'Fussilat', nameUrdu: 'فصلت', meaning: 'Explained In Detail', ayahs: 54, revelationType: 'Meccan' },
  { number: 42, nameArabic: 'الشورى', nameEnglish: 'Ash-Shura', nameUrdu: 'الشوری', meaning: 'The Consultation', ayahs: 53, revelationType: 'Meccan' },
  { number: 43, nameArabic: 'الزخرف', nameEnglish: 'Az-Zukhruf', nameUrdu: 'الزخرف', meaning: 'The Ornaments of Gold', ayahs: 89, revelationType: 'Meccan' },
  { number: 44, nameArabic: 'الدخان', nameEnglish: 'Ad-Dukhan', nameUrdu: 'الدخان', meaning: 'The Smoke', ayahs: 59, revelationType: 'Meccan' },
  { number: 45, nameArabic: 'الجاثية', nameEnglish: 'Al-Jathiyah', nameUrdu: 'الجاثیہ', meaning: 'The Crouching', ayahs: 37, revelationType: 'Meccan' },
  { number: 46, nameArabic: 'الأحقاف', nameEnglish: 'Al-Ahqaf', nameUrdu: 'الاحقاف', meaning: 'The Wind-Curved Sandhills', ayahs: 35, revelationType: 'Meccan' },
  { number: 47, nameArabic: 'محمد', nameEnglish: 'Muhammad', nameUrdu: 'محمد', meaning: 'Muhammad', ayahs: 38, revelationType: 'Medinan' },
  { number: 48, nameArabic: 'الفتح', nameEnglish: 'Al-Fath', nameUrdu: 'الفتح', meaning: 'The Victory', ayahs: 29, revelationType: 'Medinan' },
  { number: 49, nameArabic: 'الحجرات', nameEnglish: 'Al-Hujurat', nameUrdu: 'الحجرات', meaning: 'The Rooms', ayahs: 18, revelationType: 'Medinan' },
  { number: 50, nameArabic: 'ق', nameEnglish: 'Qaf', nameUrdu: 'ق', meaning: 'The Letter Qaf', ayahs: 45, revelationType: 'Meccan' },
  { number: 51, nameArabic: 'الذاريات', nameEnglish: 'Adh-Dhariyat', nameUrdu: 'الذاریات', meaning: 'The Winnowing Winds', ayahs: 60, revelationType: 'Meccan' },
  { number: 52, nameArabic: 'الطور', nameEnglish: 'At-Tur', nameUrdu: 'الطور', meaning: 'The Mount', ayahs: 49, revelationType: 'Meccan' },
  { number: 53, nameArabic: 'النجم', nameEnglish: 'An-Najm', nameUrdu: 'النجم', meaning: 'The Star', ayahs: 62, revelationType: 'Meccan' },
  { number: 54, nameArabic: 'القمر', nameEnglish: 'Al-Qamar', nameUrdu: 'القمر', meaning: 'The Moon', ayahs: 55, revelationType: 'Meccan' },
  { number: 55, nameArabic: 'الرحمن', nameEnglish: 'Ar-Rahman', nameUrdu: 'الرحمن', meaning: 'The Beneficent', ayahs: 78, revelationType: 'Medinan' },
  { number: 56, nameArabic: 'الواقعة', nameEnglish: "Al-Waqi'ah", nameUrdu: 'الواقعہ', meaning: 'The Inevitable', ayahs: 96, revelationType: 'Meccan' },
  { number: 57, nameArabic: 'الحديد', nameEnglish: 'Al-Hadid', nameUrdu: 'الحدید', meaning: 'The Iron', ayahs: 29, revelationType: 'Medinan' },
  { number: 58, nameArabic: 'المجادلة', nameEnglish: 'Al-Mujadila', nameUrdu: 'المجادلہ', meaning: 'The Pleading Woman', ayahs: 22, revelationType: 'Medinan' },
  { number: 59, nameArabic: 'الحشر', nameEnglish: 'Al-Hashr', nameUrdu: 'الحشر', meaning: 'The Exile', ayahs: 24, revelationType: 'Medinan' },
  { number: 60, nameArabic: 'الممتحنة', nameEnglish: 'Al-Mumtahanah', nameUrdu: 'الممتحنہ', meaning: 'She That is to be Examined', ayahs: 13, revelationType: 'Medinan' },
  { number: 61, nameArabic: 'الصف', nameEnglish: 'As-Saf', nameUrdu: 'الصف', meaning: 'The Ranks', ayahs: 14, revelationType: 'Medinan' },
  { number: 62, nameArabic: 'الجمعة', nameEnglish: "Al-Jumu'ah", nameUrdu: 'الجمعہ', meaning: 'The Congregation, Friday', ayahs: 11, revelationType: 'Medinan' },
  { number: 63, nameArabic: 'المنافقون', nameEnglish: 'Al-Munafiqun', nameUrdu: 'المنافقون', meaning: 'The Hypocrites', ayahs: 11, revelationType: 'Medinan' },
  { number: 64, nameArabic: 'التغابن', nameEnglish: 'At-Taghabun', nameUrdu: 'التغابن', meaning: 'The Mutual Disillusion', ayahs: 18, revelationType: 'Medinan' },
  { number: 65, nameArabic: 'الطلاق', nameEnglish: 'At-Talaq', nameUrdu: 'الطلاق', meaning: 'The Divorce', ayahs: 12, revelationType: 'Medinan' },
  { number: 66, nameArabic: 'التحريم', nameEnglish: 'At-Tahrim', nameUrdu: 'التحریم', meaning: 'The Prohibition', ayahs: 12, revelationType: 'Medinan' },
  { number: 67, nameArabic: 'الملك', nameEnglish: 'Al-Mulk', nameUrdu: 'الملک', meaning: 'The Sovereignty', ayahs: 30, revelationType: 'Meccan' },
  { number: 68, nameArabic: 'القلم', nameEnglish: 'Al-Qalam', nameUrdu: 'القلم', meaning: 'The Pen', ayahs: 52, revelationType: 'Meccan' },
  { number: 69, nameArabic: 'الحاقة', nameEnglish: "Al-Haqqah", nameUrdu: 'الحاقہ', meaning: 'The Reality', ayahs: 52, revelationType: 'Meccan' },
  { number: 70, nameArabic: 'المعارج', nameEnglish: "Al-Ma'arij", nameUrdu: 'المعارج', meaning: 'The Ascending Stairways', ayahs: 44, revelationType: 'Meccan' },
  { number: 71, nameArabic: 'نوح', nameEnglish: 'Nuh', nameUrdu: 'نوح', meaning: 'Noah', ayahs: 28, revelationType: 'Meccan' },
  { number: 72, nameArabic: 'الجن', nameEnglish: 'Al-Jinn', nameUrdu: 'الجن', meaning: 'The Jinn', ayahs: 28, revelationType: 'Meccan' },
  { number: 73, nameArabic: 'المزمل', nameEnglish: 'Al-Muzzammil', nameUrdu: 'المزمل', meaning: 'The Enshrouded One', ayahs: 20, revelationType: 'Meccan' },
  { number: 74, nameArabic: 'المدثر', nameEnglish: 'Al-Muddaththir', nameUrdu: 'المدثر', meaning: 'The Cloaked One', ayahs: 56, revelationType: 'Meccan' },
  { number: 75, nameArabic: 'القيامة', nameEnglish: 'Al-Qiyamah', nameUrdu: 'القیامہ', meaning: 'The Resurrection', ayahs: 40, revelationType: 'Meccan' },
  { number: 76, nameArabic: 'الإنسان', nameEnglish: 'Al-Insan', nameUrdu: 'الانسان', meaning: 'The Man', ayahs: 31, revelationType: 'Medinan' },
  { number: 77, nameArabic: 'المرسلات', nameEnglish: 'Al-Mursalat', nameUrdu: 'المرسلات', meaning: 'The Emissaries', ayahs: 50, revelationType: 'Meccan' },
  { number: 78, nameArabic: 'النبأ', nameEnglish: "An-Naba'", nameUrdu: 'النباء', meaning: 'The Tidings', ayahs: 40, revelationType: 'Meccan' },
  { number: 79, nameArabic: 'النازعات', nameEnglish: "An-Nazi'at", nameUrdu: 'النازعات', meaning: 'Those Who Drag Forth', ayahs: 46, revelationType: 'Meccan' },
  { number: 80, nameArabic: 'عبس', nameEnglish: 'Abasa', nameUrdu: 'عبس', meaning: 'He Frowned', ayahs: 42, revelationType: 'Meccan' },
  { number: 81, nameArabic: 'التكوير', nameEnglish: 'At-Takwir', nameUrdu: 'التکویر', meaning: 'The Overthrowing', ayahs: 29, revelationType: 'Meccan' },
  { number: 82, nameArabic: 'الانفطار', nameEnglish: 'Al-Infitar', nameUrdu: 'الانفطار', meaning: 'The Cleaving', ayahs: 19, revelationType: 'Meccan' },
  { number: 83, nameArabic: 'المطففين', nameEnglish: 'Al-Mutaffifin', nameUrdu: 'المطففین', meaning: 'The Defrauding', ayahs: 36, revelationType: 'Meccan' },
  { number: 84, nameArabic: 'الانشقاق', nameEnglish: 'Al-Inshiqaq', nameUrdu: 'الانشقاق', meaning: 'The Sundering', ayahs: 25, revelationType: 'Meccan' },
  { number: 85, nameArabic: 'البروج', nameEnglish: 'Al-Buruj', nameUrdu: 'البروج', meaning: 'The Mansions of the Stars', ayahs: 22, revelationType: 'Meccan' },
  { number: 86, nameArabic: 'الطارق', nameEnglish: 'At-Tariq', nameUrdu: 'الطارق', meaning: 'The Nightcomer', ayahs: 17, revelationType: 'Meccan' },
  { number: 87, nameArabic: 'الأعلى', nameEnglish: "Al-A'la", nameUrdu: 'الاعلی', meaning: 'The Most High', ayahs: 19, revelationType: 'Meccan' },
  { number: 88, nameArabic: 'الغاشية', nameEnglish: 'Al-Ghashiyah', nameUrdu: 'الغاشیہ', meaning: 'The Overwhelming', ayahs: 26, revelationType: 'Meccan' },
  { number: 89, nameArabic: 'الفجر', nameEnglish: 'Al-Fajr', nameUrdu: 'الفجر', meaning: 'The Dawn', ayahs: 30, revelationType: 'Meccan' },
  { number: 90, nameArabic: 'البلد', nameEnglish: 'Al-Balad', nameUrdu: 'البلد', meaning: 'The City', ayahs: 20, revelationType: 'Meccan' },
  { number: 91, nameArabic: 'الشمس', nameEnglish: 'Ash-Shams', nameUrdu: 'الشمس', meaning: 'The Sun', ayahs: 15, revelationType: 'Meccan' },
  { number: 92, nameArabic: 'الليل', nameEnglish: 'Al-Layl', nameUrdu: 'اللیل', meaning: 'The Night', ayahs: 21, revelationType: 'Meccan' },
  { number: 93, nameArabic: 'الضحى', nameEnglish: 'Ad-Duha', nameUrdu: 'الضحی', meaning: 'The Morning Hours', ayahs: 11, revelationType: 'Meccan' },
  { number: 94, nameArabic: 'الشرح', nameEnglish: 'Ash-Sharh', nameUrdu: 'الشرح', meaning: 'The Relief', ayahs: 8, revelationType: 'Meccan' },
  { number: 95, nameArabic: 'التين', nameEnglish: 'At-Tin', nameUrdu: 'التین', meaning: 'The Fig', ayahs: 8, revelationType: 'Meccan' },
  { number: 96, nameArabic: 'العلق', nameEnglish: "Al-'Alaq", nameUrdu: 'العلق', meaning: 'The Clot', ayahs: 19, revelationType: 'Meccan' },
  { number: 97, nameArabic: 'القدر', nameEnglish: 'Al-Qadr', nameUrdu: 'القدر', meaning: 'The Power', ayahs: 5, revelationType: 'Meccan' },
  { number: 98, nameArabic: 'البينة', nameEnglish: 'Al-Bayyinah', nameUrdu: 'البینہ', meaning: 'The Clear Proof', ayahs: 8, revelationType: 'Medinan' },
  { number: 99, nameArabic: 'الزلزلة', nameEnglish: 'Az-Zalzalah', nameUrdu: 'الزلزلہ', meaning: 'The Earthquake', ayahs: 8, revelationType: 'Medinan' },
  { number: 100, nameArabic: 'العاديات', nameEnglish: "Al-'Adiyat", nameUrdu: 'العادیات', meaning: 'The Courser', ayahs: 11, revelationType: 'Meccan' },
  { number: 101, nameArabic: 'القارعة', nameEnglish: "Al-Qari'ah", nameUrdu: 'القارعہ', meaning: 'The Calamity', ayahs: 11, revelationType: 'Meccan' },
  { number: 102, nameArabic: 'التكاثر', nameEnglish: 'At-Takathur', nameUrdu: 'التکاثر', meaning: 'The Rivalry in World Increase', ayahs: 8, revelationType: 'Meccan' },
  { number: 103, nameArabic: 'العصر', nameEnglish: 'Al-Asr', nameUrdu: 'العصر', meaning: 'The Declining Day', ayahs: 3, revelationType: 'Meccan' },
  { number: 104, nameArabic: 'الهمزة', nameEnglish: 'Al-Humazah', nameUrdu: 'الہمزہ', meaning: 'The Traducer', ayahs: 9, revelationType: 'Meccan' },
  { number: 105, nameArabic: 'الفيل', nameEnglish: 'Al-Fil', nameUrdu: 'الفیل', meaning: 'The Elephant', ayahs: 5, revelationType: 'Meccan' },
  { number: 106, nameArabic: 'قريش', nameEnglish: 'Quraysh', nameUrdu: 'قریش', meaning: 'Quraysh', ayahs: 4, revelationType: 'Meccan' },
  { number: 107, nameArabic: 'الماعون', nameEnglish: "Al-Ma'un", nameUrdu: 'الماعون', meaning: 'The Small Kindnesses', ayahs: 7, revelationType: 'Meccan' },
  { number: 108, nameArabic: 'الكوثر', nameEnglish: 'Al-Kawthar', nameUrdu: 'الکوثر', meaning: 'The Abundance', ayahs: 3, revelationType: 'Meccan' },
  { number: 109, nameArabic: 'الكافرون', nameEnglish: 'Al-Kafirun', nameUrdu: 'الکافرون', meaning: 'The Disbelievers', ayahs: 6, revelationType: 'Meccan' },
  { number: 110, nameArabic: 'النصر', nameEnglish: 'An-Nasr', nameUrdu: 'النصر', meaning: 'The Divine Support', ayahs: 3, revelationType: 'Medinan' },
  { number: 111, nameArabic: 'المسد', nameEnglish: 'Al-Masad', nameUrdu: 'المسد', meaning: 'The Palm Fibre', ayahs: 5, revelationType: 'Meccan' },
  { number: 112, nameArabic: 'الإخلاص', nameEnglish: 'Al-Ikhlas', nameUrdu: 'الاخلاص', meaning: 'The Sincerity', ayahs: 4, revelationType: 'Meccan' },
  { number: 113, nameArabic: 'الفلق', nameEnglish: 'Al-Falaq', nameUrdu: 'الفلق', meaning: 'The Daybreak', ayahs: 5, revelationType: 'Meccan' },
  { number: 114, nameArabic: 'الناس', nameEnglish: 'An-Nas', nameUrdu: 'الناس', meaning: 'Mankind', ayahs: 6, revelationType: 'Meccan' },
];
