export type TasbihPreset = {
  id: string;
  arabic: string;
  transliteration: string;
  translationEn: string;
  translationUr: string;
  translationAr: string;
  defaultTarget: number;
  virtue: string;
  virtueUr: string;
  virtueAr: string;
};

export const TASBIH_PRESETS: TasbihPreset[] = [
  {
    id: 'subhanallah',
    arabic: 'سُبْحَانَ اللّٰهِ',
    transliteration: 'Subhan Allah',
    translationEn: 'Glory be to Allah',
    translationUr: 'اللہ پاک ہے',
    translationAr: 'سبحان الله',
    defaultTarget: 33,
    virtue: 'Part of the post-prayer tasbih (Bukhari 843, Muslim 595).',
    virtueUr: 'نماز کے بعد کی تسبیح کا حصہ (بخاری ۸۴۳، مسلم ۵۹۵)',
    virtueAr: 'جزء من تسبيح ما بعد الصلاة (البخاري ٨٤٣، مسلم ٥٩٥)',
  },
  {
    id: 'alhamdulillah',
    arabic: 'اَلْحَمْدُ لِلّٰهِ',
    transliteration: 'Alhamdulillah',
    translationEn: 'All praise is for Allah',
    translationUr: 'تمام تعریفیں اللہ کے لیے',
    translationAr: 'الحمد لله',
    defaultTarget: 33,
    virtue: 'Fills the scales (Muslim 223).',
    virtueUr: 'یہ میزان کو بھر دیتا ہے (مسلم ۲۲۳)',
    virtueAr: 'تملأ الميزان (مسلم ٢٢٣)',
  },
  {
    id: 'allahuakbar',
    arabic: 'اَللّٰهُ أَكْبَرُ',
    transliteration: 'Allahu Akbar',
    translationEn: 'Allah is the Greatest',
    translationUr: 'اللہ سب سے بڑا ہے',
    translationAr: 'الله أكبر',
    defaultTarget: 34,
    virtue: 'Completes the 99 post-prayer dhikr (Muslim 597).',
    virtueUr: 'نماز کے بعد ۹۹ اذکار مکمل کرتی ہے (مسلم ۵۹۷)',
    virtueAr: 'يُكمل الـ٩٩ ذكر بعد الصلاة (مسلم ٥٩٧)',
  },
  {
    id: 'tahlil',
    arabic: 'لَا إِلٰهَ إِلَّا اللّٰهُ',
    transliteration: 'La ilaha illallah',
    translationEn: 'There is no god but Allah',
    translationUr: 'اللہ کے سوا کوئی معبود نہیں',
    translationAr: 'لا إله إلا الله',
    defaultTarget: 100,
    virtue: 'The best dhikr (Tirmidhi 3383, hasan).',
    virtueUr: 'بہترین ذکر (ترمذی ۳۳۸۳، حسن)',
    virtueAr: 'أفضل الذكر (الترمذي ٣٣٨٣، حسن)',
  },
  {
    id: 'istighfar',
    arabic: 'أَسْتَغْفِرُ اللّٰهَ',
    transliteration: 'Astaghfirullah',
    translationEn: 'I seek forgiveness from Allah',
    translationUr: 'میں اللہ سے بخشش مانگتا ہوں',
    translationAr: 'أستغفر الله',
    defaultTarget: 100,
    virtue: 'The Prophet ﷺ said over 70 times daily (Bukhari 6307).',
    virtueUr: 'حضور ﷺ روزانہ ۷۰ سے زائد بار پڑھتے تھے (بخاری ۶۳۰۷)',
    virtueAr: 'كان النبي ﷺ يستغفر أكثر من ٧٠ مرة يوميًا (البخاري ٦٣٠٧)',
  },
  {
    id: 'durood',
    arabic: 'اَللّٰهُمَّ صَلِّ عَلٰى مُحَمَّدٍ',
    transliteration: 'Allahumma salli ala Muhammad',
    translationEn: 'O Allah, send blessings upon Muhammad',
    translationUr: 'اے اللہ! محمد ﷺ پر درود بھیج',
    translationAr: 'اللهم صلِّ على محمد',
    defaultTarget: 100,
    virtue: 'Allah sends 10 blessings for every 1 (Muslim 408).',
    virtueUr: 'ایک بار کے بدلے اللہ دس رحمتیں نازل فرماتا ہے (مسلم ۴۰۸)',
    virtueAr: 'الله يصلي على العبد عشرًا مقابل كل صلاة (مسلم ٤٠٨)',
  },
  {
    id: 'hawqala',
    arabic: 'لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللّٰهِ',
    transliteration: 'La hawla wa la quwwata illa billah',
    translationEn: 'There is no power or might except by Allah',
    translationUr: 'نہ کوئی تدبیر ہے نہ قوت مگر اللہ کی توفیق سے',
    translationAr: 'لا حول ولا قوة إلا بالله',
    defaultTarget: 100,
    virtue: 'A treasure from Paradise (Bukhari 4205, Muslim 2704).',
    virtueUr: 'جنت کے خزانوں میں سے ایک خزانہ (بخاری ۴۲۰۵، مسلم ۲۷۰۴)',
    virtueAr: 'كنز من كنوز الجنة (البخاري ٤٢٠٥، مسلم ٢٧٠٤)',
  },
  {
    id: 'subhanallah_bihamdihi',
    arabic: 'سُبْحَانَ اللّٰهِ وَبِحَمْدِهِ',
    transliteration: 'Subhan Allahi wa bihamdihi',
    translationEn: 'Glory be to Allah and all praise is His',
    translationUr: 'اللہ پاک ہے اور تمام تعریفیں اُسی کے لیے',
    translationAr: 'سبحان الله وبحمده',
    defaultTarget: 100,
    virtue: 'Said 100 times a day — sins forgiven though they be like the foam of the sea (Bukhari 6405, Muslim 2691).',
    virtueUr: 'روزانہ ۱۰۰ بار پڑھنے سے گناہ معاف ہو جاتے ہیں چاہے سمندر کے جھاگ کے برابر ہوں (بخاری ۶۴۰۵، مسلم ۲۶۹۱)',
    virtueAr: 'من قالها مئة مرة في اليوم حُطَّت خطاياه ولو كانت مثل زبد البحر (البخاري ٦٤٠٥، مسلم ٢٦٩١)',
  },
  {
    id: 'subhanallah_azeem',
    arabic: 'سُبْحَانَ اللّٰهِ وَبِحَمْدِهِ، سُبْحَانَ اللّٰهِ الْعَظِيمِ',
    transliteration: 'Subhan Allahi wa bihamdihi, Subhan Allahil Azeem',
    translationEn: 'Glory and praise to Allah, Glory to Allah the Most Great',
    translationUr: 'اللہ پاک ہے اور تمام تعریفیں اُسی کے لیے، اللہ عظیم پاک ہے',
    translationAr: 'سبحان الله وبحمده، سبحان الله العظيم',
    defaultTarget: 100,
    virtue: 'Two words light on the tongue, heavy on the scales, beloved to the Most Merciful (Bukhari 6406, 6682).',
    virtueUr: 'دو کلمے زبان پر ہلکے، میزان میں بھاری اور رحمٰن کو محبوب ہیں (بخاری ۶۴۰۶، ۶۶۸۲)',
    virtueAr: 'كلمتان خفيفتان على اللسان، ثقيلتان في الميزان، حبيبتان إلى الرحمن (البخاري ٦٤٠٦، ٦٦٨٢)',
  },
  {
    id: 'hasbunallah',
    arabic: 'حَسْبُنَا اللّٰهُ وَنِعْمَ الْوَكِيلُ',
    transliteration: 'Hasbunallahu wa ni‘mal wakeel',
    translationEn: 'Allah is sufficient for us, and He is the best Disposer of affairs',
    translationUr: 'ہمارے لیے اللہ کافی ہے اور وہ بہترین کارساز ہے',
    translationAr: 'حسبنا الله ونعم الوكيل',
    defaultTarget: 100,
    virtue: 'Said by Ibrahim ﷺ in the fire and by the Prophet ﷺ at Uhud — a refuge in hardship (Quran 3:173, Bukhari 4563).',
    virtueUr: 'آگ میں حضرت ابراہیم ﷺ اور اُحد میں نبی کریم ﷺ نے پڑھی — مشکل میں پناہ (القرآن ۳:۱۷۳، بخاری ۴۵۶۳)',
    virtueAr: 'قالها إبراهيم ﷺ في النار والنبي ﷺ في أحد — ملجأ في الشدائد (آل عمران ١٧٣، البخاري ٤٥٦٣)',
  },
  {
    id: 'dua_yunus',
    arabic: 'لَا إِلٰهَ إِلَّا أَنْتَ سُبْحَانَكَ إِنِّي كُنْتُ مِنَ الظَّالِمِينَ',
    transliteration: 'La ilaha illa anta, subhanaka inni kuntu minaz-zalimeen',
    translationEn: 'There is no god but You; glory be to You — indeed, I was of the wrongdoers',
    translationUr: 'تیرے سوا کوئی معبود نہیں، تو پاک ہے، بے شک میں ظالموں میں سے تھا',
    translationAr: 'لا إله إلا أنت سبحانك إني كنت من الظالمين',
    defaultTarget: 40,
    virtue: 'The dua of Yunus ﷺ from the belly of the whale — whoever calls with it, Allah answers (Quran 21:87, Tirmidhi 3505).',
    virtueUr: 'حضرت یونس ﷺ کی مچھلی کے پیٹ سے دعا — جو بھی اس سے دعا کرے اللہ قبول فرماتا ہے (القرآن ۲۱:۸۷، ترمذی ۳۵۰۵)',
    virtueAr: 'دعاء يونس ﷺ من بطن الحوت — ما دعا بها أحد إلا استجاب الله له (الأنبياء ٨٧، الترمذي ٣٥٠٥)',
  },
  {
    id: 'rabbi_zidni_ilma',
    arabic: 'رَبِّ زِدْنِي عِلْمًا',
    transliteration: 'Rabbi zidni ilma',
    translationEn: 'My Lord, increase me in knowledge',
    translationUr: 'اے میرے رب! میرے علم میں اضافہ فرما',
    translationAr: 'رب زدني علما',
    defaultTarget: 100,
    virtue: 'The Quranic dua for seeking knowledge (Quran 20:114).',
    virtueUr: 'علم مانگنے کی قرآنی دعا (القرآن ۲۰:۱۱۴)',
    virtueAr: 'دعاء قرآني لطلب العلم (طه ١١٤)',
  },
];
